export const fakeDraftData = [
  {
    firstName: "Christian",
    lastName: "McCaffrey",
    playerId: "4034",
    position: "RB",
    pickNumber: 1,
    draftSlot: 1,
    team: "SF",
    round: 1,
    rosterId: 10,
    userId: "1",
    rank: 67,
    pickRank: "-3.0",
  },
  {
    firstName: "CeeDee",
    lastName: "Lamb",
    playerId: "6786",
    position: "WR",
    pickNumber: 2,
    draftSlot: 2,
    team: "DAL",
    round: 1,
    rosterId: 8,
    userId: "2",
    rank: 4,
    pickRank: "-1.4",
  },
  {
    firstName: "Bijan",
    lastName: "Robinson",
    playerId: "9509",
    position: "RB",
    pickNumber: 3,
    draftSlot: 3,
    team: "ATL",
    round: 1,
    rosterId: 3,
    userId: "3",
    rank: 4,
    pickRank: "0.0",
  },
  {
    firstName: "Tyreek",
    lastName: "Hill",
    playerId: "3321",
    position: "WR",
    pickNumber: 4,
    draftSlot: 4,
    team: "MIA",
    round: 1,
    rosterId: 6,
    userId: "4",
    rank: 22,
    pickRank: "-2.6",
  },
  {
    firstName: "Ja'Marr",
    lastName: "Chase",
    playerId: "7564",
    position: "WR",
    pickNumber: 5,
    draftSlot: 5,
    team: "CIN",
    round: 1,
    rosterId: 11,
    userId: "5",
    rank: 1,
    pickRank: "2.6",
  },
  {
    firstName: "Breece",
    lastName: "Hall",
    playerId: "8155",
    position: "RB",
    pickNumber: 6,
    draftSlot: 6,
    team: "NYJ",
    round: 1,
    rosterId: 4,
    userId: "6",
    rank: 16,
    pickRank: "-1.7",
  },
  {
    firstName: "Justin",
    lastName: "Jefferson",
    playerId: "6794",
    position: "WR",
    pickNumber: 7,
    draftSlot: 7,
    team: "MIN",
    round: 1,
    rosterId: 7,
    userId: "7",
    rank: 2,
    pickRank: "2.3",
  },
  {
    firstName: "Amon-Ra",
    lastName: "St. Brown",
    playerId: "7547",
    position: "WR",
    pickNumber: 8,
    draftSlot: 8,
    team: "DET",
    round: 1,
    rosterId: 2,
    userId: "8",
    rank: 3,
    pickRank: "2.0",
  },
  {
    firstName: "A.J.",
    lastName: "Brown",
    playerId: "5859",
    position: "WR",
    pickNumber: 9,
    draftSlot: 9,
    team: "PHI",
    round: 1,
    rosterId: 1,
    userId: "9",
    rank: 11,
    pickRank: "-0.6",
  },
  {
    firstName: "Saquon",
    lastName: "Barkley",
    playerId: "4866",
    position: "RB",
    pickNumber: 10,
    draftSlot: 10,
    team: "PHI",
    round: 1,
    rosterId: 12,
    userId: "10",
    rank: 1,
    pickRank: "3.6",
  },
  {
    firstName: "Jahmyr",
    lastName: "Gibbs",
    playerId: "9221",
    position: "RB",
    pickNumber: 11,
    draftSlot: 11,
    team: "DET",
    round: 1,
    rosterId: 5,
    userId: "11",
    rank: 3,
    pickRank: "2.9",
  },
  {
    firstName: "Garrett",
    lastName: "Wilson",
    playerId: "8146",
    position: "WR",
    pickNumber: 12,
    draftSlot: 12,
    team: "NYJ",
    round: 1,
    rosterId: 9,
    userId: "12",
    rank: 9,
    pickRank: "0.7",
  },
  {
    firstName: "Chris",
    lastName: "Olave",
    playerId: "8144",
    position: "WR",
    pickNumber: 24,
    draftSlot: 1,
    team: "NO",
    round: 2,
    rosterId: 10,
    userId: "1",
    rank: 90,
    pickRank: "-2.9",
  },
  {
    firstName: "Davante",
    lastName: "Adams",
    playerId: "2133",
    position: "WR",
    pickNumber: 23,
    draftSlot: 2,
    team: "LV",
    round: 2,
    rosterId: 8,
    userId: "2",
    rank: 10,
    pickRank: "1.3",
  },
  {
    firstName: "Mike",
    lastName: "Evans",
    playerId: "2216",
    position: "WR",
    pickNumber: 22,
    draftSlot: 3,
    team: "TB",
    round: 2,
    rosterId: 3,
    userId: "3",
    rank: 19,
    pickRank: "0.2",
  },
  {
    firstName: "Drake",
    lastName: "London",
    playerId: "8112",
    position: "WR",
    pickNumber: 21,
    draftSlot: 4,
    team: "ATL",
    round: 2,
    rosterId: 6,
    userId: "4",
    rank: 8,
    pickRank: "1.4",
  },
  {
    firstName: "Puka",
    lastName: "Nacua",
    playerId: "9493",
    position: "WR",
    pickNumber: 20,
    draftSlot: 5,
    team: "LAR",
    round: 2,
    rosterId: 11,
    userId: "5",
    rank: 27,
    pickRank: "-0.5",
  },
  {
    firstName: "Derrick",
    lastName: "Henry",
    playerId: "3198",
    position: "RB",
    pickNumber: 19,
    draftSlot: 6,
    team: "BAL",
    round: 2,
    rosterId: 4,
    userId: "6",
    rank: 2,
    pickRank: "3.0",
  },
  {
    firstName: "Josh",
    lastName: "Allen",
    playerId: "4984",
    position: "QB",
    pickNumber: 18,
    draftSlot: 7,
    team: "BUF",
    round: 2,
    rosterId: 7,
    userId: "7",
    rank: 2,
    pickRank: "1.7",
  },
  {
    firstName: "Travis",
    lastName: "Etienne",
    playerId: "7543",
    position: "RB",
    pickNumber: 17,
    draftSlot: 8,
    team: "JAX",
    round: 2,
    rosterId: 2,
    userId: "8",
    rank: 39,
    pickRank: "-1.7",
  },
  {
    firstName: "Josh",
    lastName: "Jacobs",
    playerId: "5850",
    position: "RB",
    pickNumber: 16,
    draftSlot: 9,
    team: "GB",
    round: 2,
    rosterId: 1,
    userId: "9",
    rank: 5,
    pickRank: "2.3",
  },
  {
    firstName: "Kyren",
    lastName: "Williams",
    playerId: "8150",
    position: "RB",
    pickNumber: 15,
    draftSlot: 10,
    team: "LAR",
    round: 2,
    rosterId: 12,
    userId: "10",
    rank: 6,
    pickRank: "2.0",
  },
  {
    firstName: "Jonathan",
    lastName: "Taylor",
    playerId: "6813",
    position: "RB",
    pickNumber: 14,
    draftSlot: 11,
    team: "IND",
    round: 2,
    rosterId: 5,
    userId: "11",
    rank: 17,
    pickRank: "-0.5",
  },
  {
    firstName: "Marvin",
    lastName: "Harrison",
    playerId: "11628",
    position: "WR",
    pickNumber: 13,
    draftSlot: 12,
    team: "ARI",
    round: 2,
    rosterId: 9,
    userId: "12",
    rank: 35,
    pickRank: "-2.3",
  },
  {
    firstName: "Isiah",
    lastName: "Pacheco",
    playerId: "8205",
    position: "RB",
    pickNumber: 25,
    draftSlot: 1,
    team: "KC",
    round: 3,
    rosterId: 10,
    userId: "1",
    rank: 61,
    pickRank: "-1.7",
  },
  {
    firstName: "Travis",
    lastName: "Kelce",
    playerId: "1466",
    position: "TE",
    pickNumber: 26,
    draftSlot: 2,
    team: "KC",
    round: 3,
    rosterId: 8,
    userId: "2",
    rank: 6,
    pickRank: "2.4",
  },
  {
    firstName: "Cooper",
    lastName: "Kupp",
    playerId: "4039",
    position: "WR",
    pickNumber: 27,
    draftSlot: 3,
    team: "LAR",
    round: 3,
    rosterId: 3,
    userId: "3",
    rank: 34,
    pickRank: "-0.3",
  },
  {
    firstName: "Nico",
    lastName: "Collins",
    playerId: "7569",
    position: "WR",
    pickNumber: 28,
    draftSlot: 4,
    team: "HOU",
    round: 3,
    rosterId: 6,
    userId: "4",
    rank: 18,
    pickRank: "0.6",
  },
  {
    firstName: "Jalen",
    lastName: "Hurts",
    playerId: "6904",
    position: "QB",
    pickNumber: 29,
    draftSlot: 5,
    team: "PHI",
    round: 3,
    rosterId: 11,
    userId: "5",
    rank: 6,
    pickRank: "1.1",
  },
  {
    firstName: "Deebo",
    lastName: "Samuel",
    playerId: "5872",
    position: "WR",
    pickNumber: 30,
    draftSlot: 6,
    team: "SF",
    round: 3,
    rosterId: 4,
    userId: "6",
    rank: 40,
    pickRank: "-0.3",
  },
  {
    firstName: "De'Von",
    lastName: "Achane",
    playerId: "9226",
    position: "RB",
    pickNumber: 31,
    draftSlot: 7,
    team: "MIA",
    round: 3,
    rosterId: 7,
    userId: "7",
    rank: 7,
    pickRank: "1.9",
  },
  {
    firstName: "Rachaad",
    lastName: "White",
    playerId: "8136",
    position: "RB",
    pickNumber: 32,
    draftSlot: 8,
    team: "TB",
    round: 3,
    rosterId: 2,
    userId: "8",
    rank: 22,
    pickRank: "0.5",
  },
  {
    firstName: "James",
    lastName: "Cook",
    playerId: "8138",
    position: "RB",
    pickNumber: 33,
    draftSlot: 9,
    team: "BUF",
    round: 3,
    rosterId: 1,
    userId: "9",
    rank: 9,
    pickRank: "1.8",
  },
  {
    firstName: "Stefon",
    lastName: "Diggs",
    playerId: "2449",
    position: "WR",
    pickNumber: 34,
    draftSlot: 10,
    team: "HOU",
    round: 3,
    rosterId: 12,
    userId: "10",
    rank: 54,
    pickRank: "-0.5",
  },
  {
    firstName: "Brandon",
    lastName: "Aiyuk",
    playerId: "6803",
    position: "WR",
    pickNumber: 35,
    draftSlot: 11,
    team: "SF",
    round: 3,
    rosterId: 5,
    userId: "11",
    rank: 97,
    pickRank: "-1.6",
  },
  {
    firstName: "Sam",
    lastName: "LaPorta",
    playerId: "10859",
    position: "TE",
    pickNumber: 36,
    draftSlot: 12,
    team: "DET",
    round: 3,
    rosterId: 9,
    userId: "12",
    rank: 8,
    pickRank: "1.9",
  },
  {
    firstName: "Malik",
    lastName: "Nabers",
    playerId: "11632",
    position: "WR",
    pickNumber: 48,
    draftSlot: 1,
    team: "NYG",
    round: 4,
    rosterId: 10,
    userId: "1",
    rank: 12,
    pickRank: "1.3",
  },
  {
    firstName: "Aaron",
    lastName: "Jones",
    playerId: "4199",
    position: "RB",
    pickNumber: 47,
    draftSlot: 2,
    team: "MIN",
    round: 4,
    rosterId: 8,
    userId: "2",
    rank: 15,
    pickRank: "1.2",
  },
  {
    firstName: "C.J.",
    lastName: "Stroud",
    playerId: "9758",
    position: "QB",
    pickNumber: 46,
    draftSlot: 3,
    team: "HOU",
    round: 4,
    rosterId: 3,
    userId: "3",
    rank: 18,
    pickRank: "0.6",
  },
  {
    firstName: "David",
    lastName: "Montgomery",
    playerId: "5892",
    position: "RB",
    pickNumber: 45,
    draftSlot: 4,
    team: "DET",
    round: 4,
    rosterId: 6,
    userId: "4",
    rank: 14,
    pickRank: "1.3",
  },
  {
    firstName: "Alvin",
    lastName: "Kamara",
    playerId: "4035",
    position: "RB",
    pickNumber: 44,
    draftSlot: 5,
    team: "NO",
    round: 4,
    rosterId: 11,
    userId: "5",
    rank: 8,
    pickRank: "1.8",
  },
  {
    firstName: "DK",
    lastName: "Metcalf",
    playerId: "5846",
    position: "WR",
    pickNumber: 43,
    draftSlot: 6,
    team: "SEA",
    round: 4,
    rosterId: 4,
    userId: "6",
    rank: 30,
    pickRank: "0.4",
  },
  {
    firstName: "Kenneth",
    lastName: "Walker",
    playerId: "8151",
    position: "RB",
    pickNumber: 42,
    draftSlot: 7,
    team: "SEA",
    round: 4,
    rosterId: 7,
    userId: "7",
    rank: 24,
    pickRank: "0.7",
  },
  {
    firstName: "Joe",
    lastName: "Mixon",
    playerId: "4018",
    position: "RB",
    pickNumber: 41,
    draftSlot: 8,
    team: "HOU",
    round: 4,
    rosterId: 2,
    userId: "8",
    rank: 12,
    pickRank: "1.6",
  },
  {
    firstName: "Lamar",
    lastName: "Jackson",
    playerId: "4881",
    position: "QB",
    pickNumber: 40,
    draftSlot: 9,
    team: "BAL",
    round: 4,
    rosterId: 1,
    userId: "9",
    rank: 1,
    pickRank: "1.4",
  },
  {
    firstName: "DeVonta",
    lastName: "Smith",
    playerId: "7525",
    position: "WR",
    pickNumber: 39,
    draftSlot: 10,
    team: "PHI",
    round: 4,
    rosterId: 12,
    userId: "10",
    rank: 33,
    pickRank: "0.2",
  },
  {
    firstName: "DJ",
    lastName: "Moore",
    playerId: "4983",
    position: "WR",
    pickNumber: 38,
    draftSlot: 11,
    team: "CHI",
    round: 4,
    rosterId: 5,
    userId: "11",
    rank: 13,
    pickRank: "1.0",
  },
  {
    firstName: "Jaylen",
    lastName: "Waddle",
    playerId: "7526",
    position: "WR",
    pickNumber: 37,
    draftSlot: 12,
    team: "MIA",
    round: 4,
    rosterId: 9,
    userId: "12",
    rank: 45,
    pickRank: "-0.2",
  },
  {
    firstName: "Trey",
    lastName: "McBride",
    playerId: "8130",
    position: "TE",
    pickNumber: 49,
    draftSlot: 1,
    team: "ARI",
    round: 5,
    rosterId: 10,
    userId: "1",
    rank: 4,
    pickRank: "2.4",
  },
  {
    firstName: "Michael",
    lastName: "Pittman",
    playerId: "6819",
    position: "WR",
    pickNumber: 50,
    draftSlot: 2,
    team: "IND",
    round: 5,
    rosterId: 8,
    userId: "2",
    rank: 52,
    pickRank: "0.0",
  },
  {
    firstName: "Zay",
    lastName: "Flowers",
    playerId: "9997",
    position: "WR",
    pickNumber: 51,
    draftSlot: 3,
    team: "BAL",
    round: 5,
    rosterId: 3,
    userId: "3",
    rank: 15,
    pickRank: "1.0",
  },
  {
    firstName: "James",
    lastName: "Conner",
    playerId: "4137",
    position: "RB",
    pickNumber: 52,
    draftSlot: 4,
    team: "ARI",
    round: 5,
    rosterId: 6,
    userId: "4",
    rank: 10,
    pickRank: "1.6",
  },
  {
    firstName: "Kyle",
    lastName: "Pitts",
    playerId: "7553",
    position: "TE",
    pickNumber: 53,
    draftSlot: 5,
    team: "ATL",
    round: 5,
    rosterId: 11,
    userId: "5",
    rank: 18,
    pickRank: "1.0",
  },
  {
    firstName: "Patrick",
    lastName: "Mahomes",
    playerId: "4046",
    position: "QB",
    pickNumber: 54,
    draftSlot: 6,
    team: "KC",
    round: 5,
    rosterId: 4,
    userId: "6",
    rank: 8,
    pickRank: "0.9",
  },
  {
    firstName: "Dalton",
    lastName: "Kincaid",
    playerId: "10236",
    position: "TE",
    pickNumber: 55,
    draftSlot: 7,
    team: "BUF",
    round: 5,
    rosterId: 7,
    userId: "7",
    rank: 24,
    pickRank: "0.6",
  },
  {
    firstName: "Mark",
    lastName: "Andrews",
    playerId: "5012",
    position: "TE",
    pickNumber: 56,
    draftSlot: 8,
    team: "BAL",
    round: 5,
    rosterId: 2,
    userId: "8",
    rank: 5,
    pickRank: "2.4",
  },
  {
    firstName: "George",
    lastName: "Pickens",
    playerId: "8137",
    position: "WR",
    pickNumber: 57,
    draftSlot: 9,
    team: "PIT",
    round: 5,
    rosterId: 1,
    userId: "9",
    rank: 38,
    pickRank: "0.3",
  },
  {
    firstName: "Amari",
    lastName: "Cooper",
    playerId: "2309",
    position: "WR",
    pickNumber: 58,
    draftSlot: 10,
    team: "CLE",
    round: 5,
    rosterId: 12,
    userId: "10",
    rank: 65,
    pickRank: "-0.1",
  },
  {
    firstName: "Tee",
    lastName: "Higgins",
    playerId: "6801",
    position: "WR",
    pickNumber: 59,
    draftSlot: 11,
    team: "CIN",
    round: 5,
    rosterId: 5,
    userId: "11",
    rank: 31,
    pickRank: "0.5",
  },
  {
    firstName: "D'Andre",
    lastName: "Swift",
    playerId: "6790",
    position: "RB",
    pickNumber: 60,
    draftSlot: 12,
    team: "CHI",
    round: 5,
    rosterId: 9,
    userId: "12",
    rank: 19,
    pickRank: "1.0",
  },
  {
    firstName: "Rashee",
    lastName: "Rice",
    playerId: "10229",
    position: "WR",
    pickNumber: 72,
    draftSlot: 1,
    team: "KC",
    round: 6,
    rosterId: 10,
    userId: "1",
    rank: 94,
    pickRank: "-0.2",
  },
  {
    firstName: "Dak",
    lastName: "Prescott",
    playerId: "3294",
    position: "QB",
    pickNumber: 71,
    draftSlot: 2,
    team: "DAL",
    round: 6,
    rosterId: 8,
    userId: "2",
    rank: 30,
    pickRank: "0.3",
  },
  {
    firstName: "David",
    lastName: "Njoku",
    playerId: "4033",
    position: "TE",
    pickNumber: 70,
    draftSlot: 3,
    team: "CLE",
    round: 6,
    rosterId: 3,
    userId: "3",
    rank: 10,
    pickRank: "1.6",
  },
  {
    firstName: "Anthony",
    lastName: "Richardson",
    playerId: "9229",
    position: "QB",
    pickNumber: 69,
    draftSlot: 4,
    team: "IND",
    round: 6,
    rosterId: 6,
    userId: "4",
    rank: 23,
    pickRank: "0.4",
  },
  {
    firstName: "Tank",
    lastName: "Dell",
    playerId: "9502",
    position: "WR",
    pickNumber: 68,
    draftSlot: 5,
    team: "HOU",
    round: 6,
    rosterId: 11,
    userId: "5",
    rank: 44,
    pickRank: "0.3",
  },
  {
    firstName: "Jake",
    lastName: "Ferguson",
    playerId: "8110",
    position: "TE",
    pickNumber: 67,
    draftSlot: 6,
    team: "DAL",
    round: 6,
    rosterId: 4,
    userId: "6",
    rank: 26,
    pickRank: "0.7",
  },
  {
    firstName: "Keenan",
    lastName: "Allen",
    playerId: "1479",
    position: "WR",
    pickNumber: 66,
    draftSlot: 7,
    team: "CHI",
    round: 6,
    rosterId: 7,
    userId: "7",
    rank: 28,
    pickRank: "0.6",
  },
  {
    firstName: "Joe",
    lastName: "Burrow",
    playerId: "6770",
    position: "QB",
    pickNumber: 65,
    draftSlot: 8,
    team: "CIN",
    round: 6,
    rosterId: 2,
    userId: "8",
    rank: 3,
    pickRank: "1.2",
  },
  {
    firstName: "Terry",
    lastName: "McLaurin",
    playerId: "5927",
    position: "WR",
    pickNumber: 64,
    draftSlot: 9,
    team: "WAS",
    round: 6,
    rosterId: 1,
    userId: "9",
    rank: 5,
    pickRank: "1.7",
  },
  {
    firstName: "Evan",
    lastName: "Engram",
    playerId: "4066",
    position: "TE",
    pickNumber: 63,
    draftSlot: 10,
    team: "JAX",
    round: 6,
    rosterId: 12,
    userId: "10",
    rank: 30,
    pickRank: "0.6",
  },
  {
    firstName: "George",
    lastName: "Kittle",
    playerId: "4217",
    position: "TE",
    pickNumber: 62,
    draftSlot: 11,
    team: "SF",
    round: 6,
    rosterId: 5,
    userId: "11",
    rank: 2,
    pickRank: "3.3",
  },
  {
    firstName: "Kyler",
    lastName: "Murray",
    playerId: "5849",
    position: "QB",
    pickNumber: 61,
    draftSlot: 12,
    team: "ARI",
    round: 6,
    rosterId: 9,
    userId: "12",
    rank: 11,
    pickRank: "0.8",
  },
  {
    firstName: "Rhamondre",
    lastName: "Stevenson",
    playerId: "7611",
    position: "RB",
    pickNumber: 73,
    draftSlot: 1,
    team: "NE",
    round: 7,
    rosterId: 10,
    userId: "1",
    rank: 23,
    pickRank: "0.9",
  },
  {
    firstName: "Najee",
    lastName: "Harris",
    playerId: "7528",
    position: "RB",
    pickNumber: 74,
    draftSlot: 2,
    team: "PIT",
    round: 7,
    rosterId: 8,
    userId: "2",
    rank: 21,
    pickRank: "0.9",
  },
  {
    firstName: "Javonte",
    lastName: "Williams",
    playerId: "7588",
    position: "RB",
    pickNumber: 75,
    draftSlot: 3,
    team: "DEN",
    round: 7,
    rosterId: 3,
    userId: "3",
    rank: 31,
    pickRank: "0.6",
  },
  {
    firstName: "Tony",
    lastName: "Pollard",
    playerId: "5967",
    position: "RB",
    pickNumber: 76,
    draftSlot: 4,
    team: "TEN",
    round: 7,
    rosterId: 6,
    userId: "4",
    rank: 20,
    pickRank: "1.0",
  },
  {
    firstName: "Raheem",
    lastName: "Mostert",
    playerId: "2749",
    position: "RB",
    pickNumber: 77,
    draftSlot: 5,
    team: "MIA",
    round: 7,
    rosterId: 11,
    userId: "5",
    rank: 57,
    pickRank: "0.2",
  },
  {
    firstName: "Chris",
    lastName: "Godwin",
    playerId: "4037",
    position: "WR",
    pickNumber: 78,
    draftSlot: 6,
    team: "TB",
    round: 7,
    rosterId: 4,
    userId: "6",
    rank: 46,
    pickRank: "0.3",
  },
  {
    firstName: "Christian",
    lastName: "Kirk",
    playerId: "4950",
    position: "WR",
    pickNumber: 79,
    draftSlot: 7,
    team: "JAX",
    round: 7,
    rosterId: 7,
    userId: "7",
    rank: 92,
    pickRank: "-0.1",
  },
  {
    firstName: "Calvin",
    lastName: "Ridley",
    playerId: "4981",
    position: "WR",
    pickNumber: 80,
    draftSlot: 8,
    team: "TEN",
    round: 7,
    rosterId: 2,
    userId: "8",
    rank: 29,
    pickRank: "0.6",
  },
  {
    firstName: "Nick",
    lastName: "Chubb",
    playerId: "4988",
    position: "RB",
    pickNumber: 81,
    draftSlot: 9,
    team: "CLE",
    round: 7,
    rosterId: 1,
    userId: "9",
    rank: 56,
    pickRank: "0.3",
  },
  {
    firstName: "Zamir",
    lastName: "White",
    playerId: "8139",
    position: "RB",
    pickNumber: 82,
    draftSlot: 10,
    team: "LV",
    round: 7,
    rosterId: 12,
    userId: "10",
    rank: 77,
    pickRank: "0.1",
  },
  {
    firstName: "Jayden",
    lastName: "Reed",
    playerId: "10222",
    position: "WR",
    pickNumber: 83,
    draftSlot: 11,
    team: "GB",
    round: 7,
    rosterId: 5,
    userId: "11",
    rank: 20,
    pickRank: "0.8",
  },
  {
    firstName: "Xavier",
    lastName: "Worthy",
    playerId: "11624",
    position: "WR",
    pickNumber: 84,
    draftSlot: 12,
    team: "KC",
    round: 7,
    rosterId: 9,
    userId: "12",
    rank: 23,
    pickRank: "0.8",
  },
  {
    firstName: "Jaxon",
    lastName: "Smith-Njigba",
    playerId: "9488",
    position: "WR",
    pickNumber: 96,
    draftSlot: 1,
    team: "SEA",
    round: 8,
    rosterId: 10,
    userId: "1",
    rank: 7,
    pickRank: "1.3",
  },
  {
    firstName: "Keon",
    lastName: "Coleman",
    playerId: "11637",
    position: "WR",
    pickNumber: 95,
    draftSlot: 2,
    team: "BUF",
    round: 8,
    rosterId: 8,
    userId: "2",
    rank: 69,
    pickRank: "0.2",
  },
  {
    firstName: "Christian",
    lastName: "Watson",
    playerId: "8167",
    position: "WR",
    pickNumber: 94,
    draftSlot: 3,
    team: "GB",
    round: 8,
    rosterId: 3,
    userId: "3",
    rank: 63,
    pickRank: "0.2",
  },
  {
    firstName: "Jordan",
    lastName: "Addison",
    playerId: "9756",
    position: "WR",
    pickNumber: 93,
    draftSlot: 4,
    team: "MIN",
    round: 8,
    rosterId: 6,
    userId: "4",
    rank: 17,
    pickRank: "1.0",
  },
  {
    firstName: "Devin",
    lastName: "Singletary",
    playerId: "6130",
    position: "RB",
    pickNumber: 92,
    draftSlot: 5,
    team: "NYG",
    round: 8,
    rosterId: 11,
    userId: "5",
    rank: 44,
    pickRank: "0.4",
  },
  {
    firstName: "Brian",
    lastName: "Robinson",
    playerId: "8154",
    position: "RB",
    pickNumber: 91,
    draftSlot: 6,
    team: "WAS",
    round: 8,
    rosterId: 4,
    userId: "6",
    rank: 30,
    pickRank: "0.8",
  },
  {
    firstName: "Ladd",
    lastName: "McConkey",
    playerId: "11635",
    position: "WR",
    pickNumber: 90,
    draftSlot: 7,
    team: "LAC",
    round: 8,
    rosterId: 7,
    userId: "7",
    rank: 21,
    pickRank: "0.8",
  },
  {
    firstName: "Gus",
    lastName: "Edwards",
    playerId: "5248",
    position: "RB",
    pickNumber: 89,
    draftSlot: 8,
    team: "LAC",
    round: 8,
    rosterId: 2,
    userId: "8",
    rank: 55,
    pickRank: "0.3",
  },
  {
    firstName: "Jerome",
    lastName: "Ford",
    playerId: "8143",
    position: "RB",
    pickNumber: 88,
    draftSlot: 9,
    team: "CLE",
    round: 8,
    rosterId: 1,
    userId: "9",
    rank: 32,
    pickRank: "0.7",
  },
  {
    firstName: "Diontae",
    lastName: "Johnson",
    playerId: "5937",
    position: "WR",
    pickNumber: 87,
    draftSlot: 10,
    team: "CAR",
    round: 8,
    rosterId: 12,
    userId: "10",
    rank: 78,
    pickRank: "0.1",
  },
  {
    firstName: "Zack",
    lastName: "Moss",
    playerId: "6845",
    position: "RB",
    pickNumber: 86,
    draftSlot: 11,
    team: "CIN",
    round: 8,
    rosterId: 5,
    userId: "11",
    rank: 49,
    pickRank: "0.4",
  },
  {
    firstName: "Austin",
    lastName: "Ekeler",
    playerId: "4663",
    position: "RB",
    pickNumber: 85,
    draftSlot: 12,
    team: "WAS",
    round: 8,
    rosterId: 9,
    userId: "12",
    rank: 34,
    pickRank: "0.6",
  },
  {
    firstName: "Jordan",
    lastName: "Love",
    playerId: "6804",
    position: "QB",
    pickNumber: 97,
    draftSlot: 1,
    team: "GB",
    round: 9,
    rosterId: 10,
    userId: "1",
    rank: 17,
    pickRank: "0.6",
  },
  {
    firstName: "Ezekiel",
    lastName: "Elliott",
    playerId: "3164",
    position: "RB",
    pickNumber: 98,
    draftSlot: 2,
    team: "DAL",
    round: 9,
    rosterId: 8,
    userId: "2",
    rank: 60,
    pickRank: "0.3",
  },
  {
    firstName: "Khalil",
    lastName: "Shakir",
    playerId: "8134",
    position: "WR",
    pickNumber: 99,
    draftSlot: 3,
    team: "BUF",
    round: 9,
    rosterId: 3,
    userId: "3",
    rank: 32,
    pickRank: "0.6",
  },
  {
    firstName: "Brock",
    lastName: "Bowers",
    playerId: "11604",
    position: "TE",
    pickNumber: 100,
    draftSlot: 4,
    team: "LV",
    round: 9,
    rosterId: 6,
    userId: "4",
    rank: 1,
    pickRank: "3.1",
  },
  {
    firstName: "Rome",
    lastName: "Odunze",
    playerId: "11620",
    position: "WR",
    pickNumber: 101,
    draftSlot: 5,
    team: "CHI",
    round: 9,
    rosterId: 11,
    userId: "5",
    rank: 42,
    pickRank: "0.4",
  },
  {
    firstName: "DeAndre",
    lastName: "Hopkins",
    playerId: "1426",
    position: "WR",
    pickNumber: 102,
    draftSlot: 6,
    team: "TEN",
    round: 9,
    rosterId: 4,
    userId: "6",
    rank: 41,
    pickRank: "0.4",
  },
  {
    firstName: "Jonathon",
    lastName: "Brooks",
    playerId: "11583",
    position: "RB",
    pickNumber: 103,
    draftSlot: 7,
    team: "CAR",
    round: 9,
    rosterId: 7,
    userId: "7",
    rank: 104,
    pickRank: "0.0",
  },
  {
    firstName: "Jameson",
    lastName: "Williams",
    playerId: "8148",
    position: "WR",
    pickNumber: 104,
    draftSlot: 8,
    team: "DET",
    round: 9,
    rosterId: 2,
    userId: "8",
    rank: 25,
    pickRank: "0.7",
  },
  {
    firstName: "Courtland",
    lastName: "Sutton",
    playerId: "5045",
    position: "WR",
    pickNumber: 105,
    draftSlot: 9,
    team: "DEN",
    round: 9,
    rosterId: 1,
    userId: "9",
    rank: 16,
    pickRank: "1.0",
  },
  {
    firstName: "Dallas",
    lastName: "Goedert",
    playerId: "5022",
    position: "TE",
    pickNumber: 106,
    draftSlot: 10,
    team: "PHI",
    round: 9,
    rosterId: 12,
    userId: "10",
    rank: 25,
    pickRank: "0.8",
  },
  {
    firstName: "Hollywood",
    lastName: "Brown",
    playerId: "5848",
    position: "WR",
    pickNumber: 107,
    draftSlot: 11,
    team: "KC",
    round: 9,
    rosterId: 5,
    userId: "11",
    rank: 143,
    pickRank: "-0.2",
  },
  {
    firstName: "Jaylen",
    lastName: "Warren",
    playerId: "8228",
    position: "RB",
    pickNumber: 108,
    draftSlot: 12,
    team: "PIT",
    round: 9,
    rosterId: 9,
    userId: "12",
    rank: 38,
    pickRank: "0.5",
  },
  {
    firstName: "Jayden",
    lastName: "Daniels",
    playerId: "11566",
    position: "QB",
    pickNumber: 120,
    draftSlot: 1,
    team: "WAS",
    round: 10,
    rosterId: 10,
    userId: "1",
    rank: 4,
    pickRank: "1.0",
  },
  {
    firstName: "Tyler",
    lastName: "Lockett",
    playerId: "2374",
    position: "WR",
    pickNumber: 119,
    draftSlot: 2,
    team: "SEA",
    round: 10,
    rosterId: 8,
    userId: "2",
    rank: 59,
    pickRank: "0.3",
  },
  {
    firstName: "J.K.",
    lastName: "Dobbins",
    playerId: "6806",
    position: "RB",
    pickNumber: 118,
    draftSlot: 3,
    team: "LAC",
    round: 10,
    rosterId: 3,
    userId: "3",
    rank: 27,
    pickRank: "0.9",
  },
  {
    firstName: "T.J.",
    lastName: "Hockenson",
    playerId: "5844",
    position: "TE",
    pickNumber: 117,
    draftSlot: 4,
    team: "MIN",
    round: 10,
    rosterId: 6,
    userId: "4",
    rank: 33,
    pickRank: "0.7",
  },
  {
    firstName: "Tyjae",
    lastName: "Spears",
    playerId: "9508",
    position: "RB",
    pickNumber: 116,
    draftSlot: 5,
    team: "TEN",
    round: 10,
    rosterId: 11,
    userId: "5",
    rank: 43,
    pickRank: "0.5",
  },
  {
    firstName: "Chase",
    lastName: "Brown",
    playerId: "9224",
    position: "RB",
    pickNumber: 115,
    draftSlot: 6,
    team: "CIN",
    round: 10,
    rosterId: 4,
    userId: "6",
    rank: 13,
    pickRank: "1.3",
  },
  {
    firstName: "Trey",
    lastName: "Benson",
    playerId: "11589",
    position: "RB",
    pickNumber: 114,
    draftSlot: 7,
    team: "ARI",
    round: 10,
    rosterId: 7,
    userId: "7",
    rank: 65,
    pickRank: "0.4",
  },
  {
    firstName: "Brian",
    lastName: "Thomas",
    playerId: "11631",
    position: "WR",
    pickNumber: 113,
    draftSlot: 8,
    team: "JAX",
    round: 10,
    rosterId: 2,
    userId: "8",
    rank: 6,
    pickRank: "1.6",
  },
  {
    firstName: "Dalton",
    lastName: "Schultz",
    playerId: "5001",
    position: "TE",
    pickNumber: 112,
    draftSlot: 9,
    team: "HOU",
    round: 10,
    rosterId: 1,
    userId: "9",
    rank: 19,
    pickRank: "0.8",
  },
  {
    firstName: "Justin",
    lastName: "Herbert",
    playerId: "6797",
    position: "QB",
    pickNumber: 111,
    draftSlot: 10,
    team: "LAC",
    round: 10,
    rosterId: 12,
    userId: "10",
    rank: 16,
    pickRank: "0.6",
  },
  {
    firstName: "Tua",
    lastName: "Tagovailoa",
    playerId: "6768",
    position: "QB",
    pickNumber: 110,
    draftSlot: 11,
    team: "MIA",
    round: 10,
    rosterId: 5,
    userId: "11",
    rank: 21,
    pickRank: "0.4",
  },
  {
    firstName: "Blake",
    lastName: "Corum",
    playerId: "11586",
    position: "RB",
    pickNumber: 109,
    draftSlot: 12,
    team: "LAR",
    round: 10,
    rosterId: 9,
    userId: "12",
    rank: 75,
    pickRank: "0.3",
  },
  {
    firstName: "Curtis",
    lastName: "Samuel",
    playerId: "4082",
    position: "WR",
    pickNumber: 121,
    draftSlot: 1,
    team: "BUF",
    round: 11,
    rosterId: 10,
    userId: "1",
    rank: 110,
    pickRank: "0.1",
  },
  {
    firstName: "Chuba",
    lastName: "Hubbard",
    playerId: "7594",
    position: "RB",
    pickNumber: 122,
    draftSlot: 2,
    team: "CAR",
    round: 11,
    rosterId: 8,
    userId: "2",
    rank: 11,
    pickRank: "1.6",
  },
  {
    firstName: "Brandon",
    lastName: "Aubrey",
    playerId: "11533",
    position: "K",
    pickNumber: 123,
    draftSlot: 3,
    team: "DAL",
    round: 11,
    rosterId: 3,
    userId: "3",
    rank: 2,
    pickRank: "0.5",
  },
  {
    firstName: "Romeo",
    lastName: "Doubs",
    playerId: "8121",
    position: "WR",
    pickNumber: 124,
    draftSlot: 4,
    team: "GB",
    round: 11,
    rosterId: 6,
    userId: "4",
    rank: 56,
    pickRank: "0.4",
  },
  {
    firstName: "Jakobi",
    lastName: "Meyers",
    playerId: "5947",
    position: "WR",
    pickNumber: 125,
    draftSlot: 5,
    team: "LV",
    round: 11,
    rosterId: 11,
    userId: "5",
    rank: 36,
    pickRank: "0.6",
  },
  {
    firstName: "Brock",
    lastName: "Purdy",
    playerId: "8183",
    position: "QB",
    pickNumber: 126,
    draftSlot: 6,
    team: "SF",
    round: 11,
    rosterId: 4,
    userId: "6",
    rank: 14,
    pickRank: "0.6",
  },
  {
    firstName: "Harrison",
    lastName: "Butker",
    playerId: "4227",
    position: "K",
    pickNumber: 127,
    draftSlot: 7,
    team: "KC",
    round: 11,
    rosterId: 7,
    userId: "7",
    rank: 26,
    pickRank: "0.3",
  },
  {
    firstName: "Caleb",
    lastName: "Williams",
    playerId: "11560",
    position: "QB",
    pickNumber: 128,
    draftSlot: 8,
    team: "CHI",
    round: 11,
    rosterId: 2,
    userId: "8",
    rank: 13,
    pickRank: "0.6",
  },
  {
    firstName: "Cole",
    lastName: "Kmet",
    playerId: "6826",
    position: "TE",
    pickNumber: 129,
    draftSlot: 9,
    team: "CHI",
    round: 11,
    rosterId: 1,
    userId: "9",
    rank: 15,
    pickRank: "1.2",
  },
  {
    firstName: "Zach",
    lastName: "Charbonnet",
    playerId: "9753",
    position: "RB",
    pickNumber: 130,
    draftSlot: 10,
    team: "SEA",
    round: 11,
    rosterId: 12,
    userId: "10",
    rank: 25,
    pickRank: "0.9",
  },
  {
    firstName: "Justin",
    lastName: "Tucker",
    playerId: "1264",
    position: "K",
    pickNumber: 131,
    draftSlot: 11,
    team: "BAL",
    round: 11,
    rosterId: 5,
    userId: "11",
    rank: 9,
    pickRank: "0.4",
  },
  {
    firstName: "Jared",
    lastName: "Goff",
    playerId: "3163",
    position: "QB",
    pickNumber: 132,
    draftSlot: 12,
    team: "DET",
    round: 11,
    rosterId: 9,
    userId: "12",
    rank: 7,
    pickRank: "0.8",
  },
  {
    firstName: "Ja'Lynn",
    lastName: "Polk",
    playerId: "11619",
    position: "WR",
    pickNumber: 144,
    draftSlot: 1,
    team: "NE",
    round: 12,
    rosterId: 10,
    userId: "1",
    rank: 125,
    pickRank: "0.1",
  },
  {
    firstName: "Jake",
    lastName: "Elliott",
    playerId: "4195",
    position: "K",
    pickNumber: 143,
    draftSlot: 2,
    team: "PHI",
    round: 12,
    rosterId: 8,
    userId: "2",
    rank: 12,
    pickRank: "0.4",
  },
  {
    firstName: "Joshua",
    lastName: "Palmer",
    playerId: "7670",
    position: "WR",
    pickNumber: 142,
    draftSlot: 3,
    team: "LAC",
    round: 12,
    rosterId: 3,
    userId: "3",
    rank: 68,
    pickRank: "0.3",
  },
  {
    firstName: "Younghoe",
    lastName: "Koo",
    playerId: "4666",
    position: "K",
    pickNumber: 141,
    draftSlot: 4,
    team: "ATL",
    round: 12,
    rosterId: 6,
    userId: "4",
    rank: 14,
    pickRank: "0.4",
  },
  {
    firstName: "Luke",
    lastName: "Musgrave",
    playerId: "9481",
    position: "TE",
    pickNumber: 140,
    draftSlot: 5,
    team: "GB",
    round: 12,
    rosterId: 11,
    userId: "5",
    rank: 92,
    pickRank: "0.3",
  },
  {
    firstName: "Rashid",
    lastName: "Shaheed",
    playerId: "8676",
    position: "WR",
    pickNumber: 139,
    draftSlot: 6,
    team: "NO",
    round: 12,
    rosterId: 4,
    userId: "6",
    rank: 80,
    pickRank: "0.3",
  },
  {
    firstName: "Mike",
    lastName: "Williams",
    playerId: "4068",
    position: "WR",
    pickNumber: 138,
    draftSlot: 7,
    team: "NYJ",
    round: 12,
    rosterId: 7,
    userId: "7",
    rank: 106,
    pickRank: "0.1",
  },
  {
    firstName: "Ka'imi",
    lastName: "Fairbairn",
    playerId: "3451",
    position: "K",
    pickNumber: 137,
    draftSlot: 8,
    team: "HOU",
    round: 12,
    rosterId: 2,
    userId: "8",
    rank: 3,
    pickRank: "0.5",
  },
  {
    firstName: "New York",
    lastName: "Jets",
    playerId: "NYJ",
    position: "DEF",
    pickNumber: 136,
    draftSlot: 9,
    team: "NYJ",
    round: 12,
    rosterId: 1,
    userId: "9",
    rank: 23,
    pickRank: "0.3",
  },
  {
    firstName: "Adonai",
    lastName: "Mitchell",
    playerId: "11625",
    position: "WR",
    pickNumber: 135,
    draftSlot: 10,
    team: "IND",
    round: 12,
    rosterId: 12,
    userId: "10",
    rank: 112,
    pickRank: "0.1",
  },
  {
    firstName: "Tyler",
    lastName: "Allgeier",
    playerId: "8132",
    position: "RB",
    pickNumber: 134,
    draftSlot: 11,
    team: "ATL",
    round: 12,
    rosterId: 5,
    userId: "11",
    rank: 41,
    pickRank: "0.6",
  },
  {
    firstName: "Pat",
    lastName: "Freiermuth",
    playerId: "7600",
    position: "TE",
    pickNumber: 133,
    draftSlot: 12,
    team: "PIT",
    round: 12,
    rosterId: 9,
    userId: "12",
    rank: 9,
    pickRank: "1.6",
  },
  {
    firstName: "Jaleel",
    lastName: "McLaughlin",
    playerId: "11439",
    position: "RB",
    pickNumber: 145,
    draftSlot: 1,
    team: "DEN",
    round: 13,
    rosterId: 10,
    userId: "1",
    rank: 48,
    pickRank: "0.5",
  },
  {
    firstName: "San Francisco",
    lastName: "49ers",
    playerId: "SF",
    position: "DEF",
    pickNumber: 146,
    draftSlot: 2,
    team: "SF",
    round: 13,
    rosterId: 8,
    userId: "2",
    rank: 22,
    pickRank: "0.3",
  },
  {
    firstName: "Ty",
    lastName: "Chandler",
    playerId: "8230",
    position: "RB",
    pickNumber: 147,
    draftSlot: 3,
    team: "MIN",
    round: 13,
    rosterId: 3,
    userId: "3",
    rank: 79,
    pickRank: "0.4",
  },
  {
    firstName: "Cleveland",
    lastName: "Browns",
    playerId: "CLE",
    position: "DEF",
    pickNumber: 148,
    draftSlot: 4,
    team: "CLE",
    round: 13,
    rosterId: 6,
    userId: "4",
    rank: 25,
    pickRank: "0.3",
  },
  {
    firstName: "Evan",
    lastName: "McPherson",
    playerId: "7839",
    position: "K",
    pickNumber: 149,
    draftSlot: 5,
    team: "CIN",
    round: 13,
    rosterId: 11,
    userId: "5",
    rank: 28,
    pickRank: "0.3",
  },
  {
    firstName: "Baltimore",
    lastName: "Ravens",
    playerId: "BAL",
    position: "DEF",
    pickNumber: 150,
    draftSlot: 6,
    team: "BAL",
    round: 13,
    rosterId: 4,
    userId: "6",
    rank: 14,
    pickRank: "0.4",
  },
  {
    firstName: "Rico",
    lastName: "Dowdle",
    playerId: "7021",
    position: "RB",
    pickNumber: 151,
    draftSlot: 7,
    team: "DAL",
    round: 13,
    rosterId: 7,
    userId: "7",
    rank: 26,
    pickRank: "0.9",
  },
  {
    firstName: "Dallas",
    lastName: "Cowboys",
    playerId: "DAL",
    position: "DEF",
    pickNumber: 152,
    draftSlot: 8,
    team: "DAL",
    round: 13,
    rosterId: 2,
    userId: "8",
    rank: 8,
    pickRank: "0.4",
  },
  {
    firstName: "Jake",
    lastName: "Moody",
    playerId: "10937",
    position: "K",
    pickNumber: 153,
    draftSlot: 9,
    team: "SF",
    round: 13,
    rosterId: 1,
    userId: "9",
    rank: 23,
    pickRank: "0.3",
  },
  {
    firstName: "Jerry",
    lastName: "Jeudy",
    playerId: "6783",
    position: "WR",
    pickNumber: 154,
    draftSlot: 10,
    team: "CLE",
    round: 13,
    rosterId: 12,
    userId: "10",
    rank: 14,
    pickRank: "1.1",
  },
  {
    firstName: "Taysom",
    lastName: "Hill",
    playerId: "4381",
    position: "TE",
    pickNumber: 155,
    draftSlot: 11,
    team: "NO",
    round: 13,
    rosterId: 5,
    userId: "11",
    rank: 17,
    pickRank: "1.2",
  },
  {
    firstName: "Jaylen",
    lastName: "Wright",
    playerId: "11643",
    position: "RB",
    pickNumber: 156,
    draftSlot: 12,
    team: "MIA",
    round: 13,
    rosterId: 9,
    userId: "12",
    rank: 78,
    pickRank: "0.4",
  },
  {
    firstName: "Greg",
    lastName: "Zuerlein",
    playerId: "1266",
    position: "K",
    pickNumber: 168,
    draftSlot: 1,
    team: "NYJ",
    round: 14,
    rosterId: 10,
    userId: "1",
    rank: 36,
    pickRank: "0.3",
  },
  {
    firstName: "Adam",
    lastName: "Thielen",
    playerId: "1689",
    position: "WR",
    pickNumber: 167,
    draftSlot: 2,
    team: "CAR",
    round: 14,
    rosterId: 8,
    userId: "2",
    rank: 67,
    pickRank: "0.4",
  },
  {
    firstName: "Troy",
    lastName: "Franklin",
    playerId: "11627",
    position: "WR",
    pickNumber: 166,
    draftSlot: 3,
    team: "DEN",
    round: 14,
    rosterId: 3,
    userId: "3",
    rank: 96,
    pickRank: "0.3",
  },
  {
    firstName: "Brandin",
    lastName: "Cooks",
    playerId: "2197",
    position: "WR",
    pickNumber: 165,
    draftSlot: 4,
    team: "DAL",
    round: 14,
    rosterId: 6,
    userId: "4",
    rank: 101,
    pickRank: "0.2",
  },
  {
    firstName: "Kansas City",
    lastName: "Chiefs",
    playerId: "KC",
    position: "DEF",
    pickNumber: 164,
    draftSlot: 5,
    team: "KC",
    round: 14,
    rosterId: 11,
    userId: "5",
    rank: 12,
    pickRank: "0.4",
  },
  {
    firstName: "Jason",
    lastName: "Sanders",
    playerId: "5119",
    position: "K",
    pickNumber: 163,
    draftSlot: 6,
    team: "MIA",
    round: 14,
    rosterId: 4,
    userId: "6",
    rank: 6,
    pickRank: "0.4",
  },
  {
    firstName: "Pittsburgh",
    lastName: "Steelers",
    playerId: "PIT",
    position: "DEF",
    pickNumber: 162,
    draftSlot: 7,
    team: "PIT",
    round: 14,
    rosterId: 7,
    userId: "7",
    rank: 3,
    pickRank: "0.5",
  },
  {
    firstName: "Darnell",
    lastName: "Mooney",
    playerId: "7090",
    position: "WR",
    pickNumber: 161,
    draftSlot: 8,
    team: "ATL",
    round: 14,
    rosterId: 2,
    userId: "8",
    rank: 24,
    pickRank: "0.8",
  },
  {
    firstName: "Dontayvion",
    lastName: "Wicks",
    playerId: "9486",
    position: "WR",
    pickNumber: 160,
    draftSlot: 9,
    team: "GB",
    round: 14,
    rosterId: 1,
    userId: "9",
    rank: 73,
    pickRank: "0.3",
  },
  {
    firstName: "Philadelphia",
    lastName: "Eagles",
    playerId: "PHI",
    position: "DEF",
    pickNumber: 159,
    draftSlot: 10,
    team: "PHI",
    round: 14,
    rosterId: 12,
    userId: "10",
    rank: 9,
    pickRank: "0.4",
  },
  {
    firstName: "Cincinnati",
    lastName: "Bengals",
    playerId: "CIN",
    position: "DEF",
    pickNumber: 158,
    draftSlot: 11,
    team: "CIN",
    round: 14,
    rosterId: 5,
    userId: "11",
    rank: 20,
    pickRank: "0.4",
  },
  {
    firstName: "Cameron",
    lastName: "Dicker",
    playerId: "8259",
    position: "K",
    pickNumber: 157,
    draftSlot: 12,
    team: "LAC",
    round: 14,
    rosterId: 9,
    userId: "12",
    rank: 5,
    pickRank: "0.4",
  },
  {
    firstName: "Ray",
    lastName: "Davis",
    playerId: "11575",
    position: "RB",
    pickNumber: 169,
    draftSlot: 1,
    team: "BUF",
    round: 15,
    rosterId: 10,
    userId: "1",
    rank: 40,
    pickRank: "0.6",
  },
  {
    firstName: "Braelon",
    lastName: "Allen",
    playerId: "11576",
    position: "RB",
    pickNumber: 170,
    draftSlot: 2,
    team: "NYJ",
    round: 15,
    rosterId: 8,
    userId: "2",
    rank: 50,
    pickRank: "0.6",
  },
  {
    firstName: "Dalvin",
    lastName: "Cook",
    playerId: "4029",
    position: "RB",
    pickNumber: 171,
    draftSlot: 3,
    team: "DAL",
    round: 15,
    rosterId: 3,
    userId: "3",
    rank: 110,
    pickRank: "0.3",
  },
  {
    firstName: "Tank",
    lastName: "Bigsby",
    playerId: "9225",
    position: "RB",
    pickNumber: 172,
    draftSlot: 4,
    team: "JAX",
    round: 15,
    rosterId: 6,
    userId: "4",
    rank: 33,
    pickRank: "0.8",
  },
  {
    firstName: "Aaron",
    lastName: "Rodgers",
    playerId: "96",
    position: "QB",
    pickNumber: 173,
    draftSlot: 5,
    team: "NYJ",
    round: 15,
    rosterId: 11,
    userId: "5",
    rank: 15,
    pickRank: "0.6",
  },
  {
    firstName: "MarShawn",
    lastName: "Lloyd",
    playerId: "11581",
    position: "RB",
    pickNumber: 174,
    draftSlot: 6,
    team: "GB",
    round: 15,
    rosterId: 4,
    userId: "6",
    rank: 115,
    pickRank: "0.3",
  },
  {
    firstName: "Antonio",
    lastName: "Gibson",
    playerId: "6945",
    position: "RB",
    pickNumber: 175,
    draftSlot: 7,
    team: "NE",
    round: 15,
    rosterId: 7,
    userId: "7",
    rank: 46,
    pickRank: "0.6",
  },
  {
    firstName: "Xavier",
    lastName: "Legette",
    playerId: "11626",
    position: "WR",
    pickNumber: 176,
    draftSlot: 8,
    team: "CAR",
    round: 15,
    rosterId: 2,
    userId: "8",
    rank: 64,
    pickRank: "0.4",
  },
  {
    firstName: "Bucky",
    lastName: "Irving",
    playerId: "11584",
    position: "RB",
    pickNumber: 177,
    draftSlot: 9,
    team: "TB",
    round: 15,
    rosterId: 1,
    userId: "9",
    rank: 18,
    pickRank: "1.3",
  },
  {
    firstName: "Trevor",
    lastName: "Lawrence",
    playerId: "7523",
    position: "QB",
    pickNumber: 178,
    draftSlot: 10,
    team: "JAX",
    round: 15,
    rosterId: 12,
    userId: "10",
    rank: 26,
    pickRank: "0.4",
  },
  {
    firstName: "Kirk",
    lastName: "Cousins",
    playerId: "1166",
    position: "QB",
    pickNumber: 179,
    draftSlot: 11,
    team: "ATL",
    round: 15,
    rosterId: 5,
    userId: "11",
    rank: 20,
    pickRank: "0.4",
  },
  {
    firstName: "Miami",
    lastName: "Dolphins",
    playerId: "MIA",
    position: "DEF",
    pickNumber: 180,
    draftSlot: 12,
    team: "MIA",
    round: 15,
    rosterId: 9,
    userId: "12",
    rank: 28,
    pickRank: "0.3",
  },
];
