export const fakeWeeklyPreview = [
  {
    id: 3,
    players: [
      {
        position: "QB",
        player_id: "4881",
        name: "Lamar Jackson",
        team: "BAL",
        projection: 25.66,
      },
      {
        position: "RB",
        player_id: "9509",
        name: "Bijan Robinson",
        team: "ATL",
        projection: 18.09,
      },
      {
        position: "RB",
        player_id: "8150",
        name: "Kyren Williams",
        team: "LAR",
        projection: 15.93,
      },
      {
        position: "WR",
        player_id: "5045",
        name: "Courtland Sutton",
        team: "DEN",
        projection: 11.2,
      },
      {
        position: "WR",
        player_id: "12501",
        name: "Matthew Golden",
        team: "GB",
        projection: 8.76,
      },
      {
        position: "TE",
        player_id: "5012",
        name: "Mark Andrews",
        team: "BAL",
        projection: 8.16,
      },
      {
        position: "RB",
        player_id: "6790",
        name: "D'Andre Swift",
        team: "CHI",
        projection: 11.23,
      },
      {
        position: "K",
        player_id: "6650",
        name: "Chase McLaughlin",
        team: "TB",
        projection: 9.28,
      },
      {
        position: "DEF",
        player_id: "DEN",
        name: null,
        team: "DEN",
        projection: 8.42,
      },
    ],
    total: 116.73,
  },
  {
    id: 6,
    players: [
      {
        position: "QB",
        player_id: "3163",
        name: "Jared Goff",
        team: "DET",
        projection: 20.46,
      },
      {
        position: "RB",
        player_id: "4866",
        name: "Saquon Barkley",
        team: "PHI",
        projection: 19.52,
      },
      {
        position: "RB",
        player_id: "11584",
        name: "Bucky Irving",
        team: "TB",
        projection: 16.19,
      },
      {
        position: "WR",
        player_id: "2133",
        name: "Davante Adams",
        team: "LAR",
        projection: 11.78,
      },
      {
        position: "WR",
        player_id: "11624",
        name: "Xavier Worthy",
        team: "KC",
        projection: 11.64,
      },
      {
        position: "TE",
        player_id: "12518",
        name: "Tyler Warren",
        team: "IND",
        projection: 7.42,
      },
      {
        position: "RB",
        player_id: "12507",
        name: "Omarion Hampton",
        team: "LAC",
        projection: 14.2,
      },
      {
        position: "K",
        player_id: "8259",
        name: "Cameron Dicker",
        team: "LAC",
        projection: 9.19,
      },
      {
        position: "DEF",
        player_id: "HOU",
        name: null,
        team: "HOU",
        projection: 6.79,
      },
    ],
    total: 117.19000000000001,
  },
  {
    id: 12,
    players: [
      {
        position: "QB",
        player_id: "4046",
        name: "Patrick Mahomes",
        team: "KC",
        projection: 21.52,
      },
      {
        position: "RB",
        player_id: "12527",
        name: "Ashton Jeanty",
        team: "LV",
        projection: 16.75,
      },
      {
        position: "RB",
        player_id: "6813",
        name: "Jonathan Taylor",
        team: "IND",
        projection: 16.98,
      },
      {
        position: "WR",
        player_id: "11628",
        name: "Marvin Harrison",
        team: "ARI",
        projection: 9.81,
      },
      {
        position: "WR",
        player_id: "4039",
        name: "Cooper Kupp",
        team: "SEA",
        projection: 9.94,
      },
      {
        position: "TE",
        player_id: "4217",
        name: "George Kittle",
        team: "SF",
        projection: 12.39,
      },
      {
        position: "RB",
        player_id: "4199",
        name: "Aaron Jones",
        team: "MIN",
        projection: 11.93,
      },
      {
        position: "K",
        player_id: "5095",
        name: "Daniel Carlson",
        team: "LV",
        projection: 8.87,
      },
      {
        position: "DEF",
        player_id: "ARI",
        name: null,
        team: "ARI",
        projection: 7.07,
      },
    ],
    total: 115.25999999999999,
  },
  {
    id: 10,
    players: [
      {
        position: "QB",
        player_id: "5849",
        name: "Kyler Murray",
        team: "ARI",
        projection: 20.42,
      },
      {
        position: "RB",
        player_id: "8151",
        name: "Kenneth Walker",
        team: "SEA",
        projection: 11.68,
      },
      {
        position: "RB",
        player_id: "7588",
        name: "Javonte Williams",
        team: "DAL",
        projection: 11.28,
      },
      {
        position: "WR",
        player_id: "6786",
        name: "CeeDee Lamb",
        team: "DAL",
        projection: 14.67,
      },
      {
        position: "WR",
        player_id: "5859",
        name: "A.J. Brown",
        team: "PHI",
        projection: 13.32,
      },
      {
        position: "TE",
        player_id: "8130",
        name: "Trey McBride",
        team: "ARI",
        projection: 11.53,
      },
      {
        position: "WR",
        player_id: "12526",
        name: "Tetairoa McMillan",
        team: "CAR",
        projection: 11.94,
      },
      {
        position: "K",
        player_id: "3451",
        name: "Ka'imi Fairbairn",
        team: "HOU",
        projection: 8.74,
      },
      {
        position: "DEF",
        player_id: "SEA",
        name: null,
        team: "SEA",
        projection: 6.47,
      },
    ],
    total: 110.05,
  },
  {
    id: 1,
    players: [
      {
        position: "QB",
        player_id: "6770",
        name: "Joe Burrow",
        team: "CIN",
        projection: 22.98,
      },
      {
        position: "RB",
        player_id: "4035",
        name: "Alvin Kamara",
        team: "NO",
        projection: 15.2,
      },
      {
        position: "RB",
        player_id: "8205",
        name: "Isiah Pacheco",
        team: "KC",
        projection: 11.64,
      },
      {
        position: "WR",
        player_id: "7569",
        name: "Nico Collins",
        team: "HOU",
        projection: 14.05,
      },
      {
        position: "WR",
        player_id: "8112",
        name: "Drake London",
        team: "ATL",
        projection: 13.59,
      },
      {
        position: "TE",
        player_id: "8110",
        name: "Jake Ferguson",
        team: "DAL",
        projection: 6.45,
      },
      {
        position: "WR",
        player_id: "11638",
        name: "Ricky Pearsall",
        team: "SF",
        projection: 10.83,
      },
      {
        position: "K",
        player_id: "12711",
        name: "Tyler Loop",
        team: "BAL",
        projection: 8.56,
      },
      {
        position: "DEF",
        player_id: "PHI",
        name: null,
        team: "PHI",
        projection: 8.12,
      },
    ],
    total: 111.42000000000002,
  },
  {
    id: 2,
    players: [
      {
        position: "QB",
        player_id: "8183",
        name: "Brock Purdy",
        team: "SF",
        projection: 21.36,
      },
      {
        position: "RB",
        player_id: "9224",
        name: "Chase Brown",
        team: "CIN",
        projection: 16.75,
      },
      {
        position: "RB",
        player_id: "5967",
        name: "Tony Pollard",
        team: "TEN",
        projection: 12.7,
      },
      {
        position: "WR",
        player_id: "6794",
        name: "Justin Jefferson",
        team: "MIN",
        projection: 15.98,
      },
      {
        position: "WR",
        player_id: "9488",
        name: "Jaxon Smith-Njigba",
        team: "SEA",
        projection: 12.06,
      },
      {
        position: "TE",
        player_id: "4033",
        name: "David Njoku",
        team: "CLE",
        projection: 10.97,
      },
      {
        position: "WR",
        player_id: "2216",
        name: "Mike Evans",
        team: "TB",
        projection: 13.76,
      },
      {
        position: "K",
        player_id: "7839",
        name: "Evan McPherson",
        team: "CIN",
        projection: 9.33,
      },
      {
        position: "DEF",
        player_id: "BAL",
        name: null,
        team: "BAL",
        projection: 6.31,
      },
    ],
    total: 119.22000000000001,
  },
  {
    id: 4,
    players: [
      {
        position: "QB",
        player_id: "4892",
        name: "Baker Mayfield",
        team: "TB",
        projection: 21.66,
      },
      {
        position: "RB",
        player_id: "9221",
        name: "Jahmyr Gibbs",
        team: "DET",
        projection: 18.24,
      },
      {
        position: "RB",
        player_id: "12504",
        name: "Kaleb Johnson",
        team: "PIT",
        projection: 8.56,
      },
      {
        position: "WR",
        player_id: "11635",
        name: "Ladd McConkey",
        team: "LAC",
        projection: 12.38,
      },
      {
        position: "WR",
        player_id: "5846",
        name: "DK Metcalf",
        team: "PIT",
        projection: 12.11,
      },
      {
        position: "TE",
        player_id: "11604",
        name: "Brock Bowers",
        team: "LV",
        projection: 13.12,
      },
      {
        position: "WR",
        player_id: "8148",
        name: "Jameson Williams",
        team: "DET",
        projection: 10.05,
      },
      {
        position: "K",
        player_id: "3678",
        name: "Wil Lutz",
        team: "DEN",
        projection: 8.86,
      },
      {
        position: "DEF",
        player_id: "BUF",
        name: null,
        team: "BUF",
        projection: 6.07,
      },
    ],
    total: 111.05000000000001,
  },
  {
    id: 5,
    players: [
      {
        position: "QB",
        player_id: "11563",
        name: "Bo Nix",
        team: "DEN",
        projection: 19.51,
      },
      {
        position: "RB",
        player_id: "3198",
        name: "Derrick Henry",
        team: "BAL",
        projection: 17.22,
      },
      {
        position: "RB",
        player_id: "9226",
        name: "De'Von Achane",
        team: "MIA",
        projection: 17.97,
      },
      {
        position: "WR",
        player_id: "3321",
        name: "Tyreek Hill",
        team: "MIA",
        projection: 12.91,
      },
      {
        position: "WR",
        player_id: "8146",
        name: "Garrett Wilson",
        team: "NYJ",
        projection: 11.53,
      },
      {
        position: "TE",
        player_id: "5844",
        name: "T.J. Hockenson",
        team: "MIN",
        projection: 8.83,
      },
      {
        position: "WR",
        player_id: "4983",
        name: "DJ Moore",
        team: "CHI",
        projection: 11.25,
      },
      {
        position: "K",
        player_id: "11539",
        name: "Jake Bates",
        team: "DET",
        projection: 9.04,
      },
      {
        position: "DEF",
        player_id: "MIN",
        name: null,
        team: "MIN",
        projection: 7.34,
      },
    ],
    total: 115.6,
  },
  {
    id: 7,
    players: [
      {
        position: "QB",
        player_id: "4984",
        name: "Josh Allen",
        team: "BUF",
        projection: 23.92,
      },
      {
        position: "RB",
        player_id: "8138",
        name: "James Cook",
        team: "BUF",
        projection: 13.93,
      },
      {
        position: "RB",
        player_id: "7594",
        name: "Chuba Hubbard",
        team: "CAR",
        projection: 14.18,
      },
      {
        position: "WR",
        player_id: "7564",
        name: "Ja'Marr Chase",
        team: "CIN",
        projection: 16.85,
      },
      {
        position: "WR",
        player_id: "5872",
        name: "Deebo Samuel",
        team: "WAS",
        projection: 10.93,
      },
      {
        position: "TE",
        player_id: "9484",
        name: "Tucker Kraft",
        team: "GB",
        projection: 7.49,
      },
      {
        position: "RB",
        player_id: "4137",
        name: "James Conner",
        team: "ARI",
        projection: 13.7,
      },
      {
        position: "K",
        player_id: "11533",
        name: "Brandon Aubrey",
        team: "DAL",
        projection: 9.69,
      },
      {
        position: "DEF",
        player_id: "WAS",
        name: null,
        team: "WAS",
        projection: 7.48,
      },
    ],
    total: 118.17,
  },
  {
    id: 9,
    players: [
      {
        position: "QB",
        player_id: "6904",
        name: "Jalen Hurts",
        team: "PHI",
        projection: 25.42,
      },
      {
        position: "RB",
        player_id: "5850",
        name: "Josh Jacobs",
        team: "GB",
        projection: 14.96,
      },
      {
        position: "RB",
        player_id: "12489",
        name: "RJ Harvey",
        team: "DEN",
        projection: 10.48,
      },
      {
        position: "WR",
        player_id: "7547",
        name: "Amon-Ra St. Brown",
        team: "DET",
        projection: 13.29,
      },
      {
        position: "WR",
        player_id: "5927",
        name: "Terry McLaurin",
        team: "WAS",
        projection: 12.28,
      },
      {
        position: "TE",
        player_id: "1466",
        name: "Travis Kelce",
        team: "KC",
        projection: 8.87,
      },
      {
        position: "RB",
        player_id: "7543",
        name: "Travis Etienne",
        team: "JAX",
        projection: 9.38,
      },
      {
        position: "K",
        player_id: "11786",
        name: "Cam Little",
        team: "JAX",
        projection: 9.04,
      },
      {
        position: "DEF",
        player_id: "SF",
        name: null,
        team: "SF",
        projection: 6.76,
      },
    ],
    total: 110.48,
  },
  {
    id: 11,
    players: [
      {
        position: "QB",
        player_id: "11566",
        name: "Jayden Daniels",
        team: "WAS",
        projection: 24.53,
      },
      {
        position: "RB",
        player_id: "12529",
        name: "TreVeyon Henderson",
        team: "NE",
        projection: 12.83,
      },
      {
        position: "RB",
        player_id: "8228",
        name: "Jaylen Warren",
        team: "PIT",
        projection: 11.97,
      },
      {
        position: "WR",
        player_id: "9493",
        name: "Puka Nacua",
        team: "LAR",
        projection: 13.25,
      },
      {
        position: "WR",
        player_id: "11632",
        name: "Malik Nabers",
        team: "NYG",
        projection: 14.19,
      },
      {
        position: "TE",
        player_id: "10859",
        name: "Sam LaPorta",
        team: "DET",
        projection: 8.87,
      },
      {
        position: "WR",
        player_id: "12514",
        name: "Emeka Egbuka",
        team: "TB",
        projection: 9.95,
      },
      {
        position: "K",
        player_id: "4227",
        name: "Harrison Butker",
        team: "KC",
        projection: 9.24,
      },
      {
        position: "DEF",
        player_id: "DET",
        name: null,
        team: "DET",
        projection: 6.57,
      },
    ],
    total: 111.4,
  },
  {
    id: 8,
    players: [
      {
        position: "QB",
        player_id: "3294",
        name: "Dak Prescott",
        team: "DAL",
        projection: 20.27,
      },
      {
        position: "RB",
        player_id: "4034",
        name: "Christian McCaffrey",
        team: "SF",
        projection: 18.58,
      },
      {
        position: "RB",
        player_id: "8155",
        name: "Breece Hall",
        team: "NYJ",
        projection: 12.68,
      },
      {
        position: "WR",
        player_id: "11631",
        name: "Brian Thomas",
        team: "JAX",
        projection: 12.52,
      },
      {
        position: "WR",
        player_id: "6801",
        name: "Tee Higgins",
        team: "CIN",
        projection: 12.55,
      },
      {
        position: "TE",
        player_id: "4144",
        name: "Jonnu Smith",
        team: "PIT",
        projection: 4.87,
      },
      {
        position: "RB",
        player_id: "5892",
        name: "David Montgomery",
        team: "DET",
        projection: 11.2,
      },
      {
        position: "K",
        player_id: "1945",
        name: "Chris Boswell",
        team: "PIT",
        projection: 8.58,
      },
      {
        position: "DEF",
        player_id: "PIT",
        name: null,
        team: "PIT",
        projection: 7.77,
      },
    ],
    total: 109.02,
  },
];
export const fakeTopPerformers = [
  {
    player: {
      position: "QB",
      player_id: "6770",
      name: "Joe Burrow",
      team: "CIN",
    },

    points: 36.98,
    user: "The Princess McBride",
  },
  {
    player: {
      position: "WR",
      player_id: "6801",
      name: "Tee Higgins",
      team: "CIN",
    },
    points: 34.6,
    user: "LaPorta Potty",
  },
  {
    player: {
      position: "QB",
      player_id: "11566",
      name: "Jayden Daniels",
      team: "WAS",
    },
    points: 31.78,
    user: "Baby Back Gibbs",
  },
  {
    player: {
      position: "QB",
      player_id: "8183",
      name: "Brock Purdy",
      team: "SF",
    },
    points: 30.28,
    user: "Just the Tua Us",
  },
];

export const fakeBottomPerformers = [
  {
    player: {
      position: "DEF",
      player_id: "IND",
      name: null,
      team: "IND",
    },
    points: -4,
    user: "Breece's Puffs",
  },
  {
    player: {
      position: "K",
      player_id: "3451",
      name: "Ka'imi Fairbairn",
      team: "HOU",
    },
    points: 0,
    user: "Bijan Mustard",
  },
  {
    player: {
      position: "WR",
      player_id: "5927",
      name: "Terry McLaurin",
      team: "WAS",
    },
    points: 1,
    user: "Saquondo ",
  },
  {
    player: {
      position: "RB",
      player_id: "9757",
      name: "Kendre Miller",
      team: "NO",
    },
    points: 2.4,
    user: "Ja’Marr the Merrier",
  },
];

export const fakeBenchPerformers = [
  {
    player: {
      position: "QB",
      player_id: "4046",
      name: "Patrick Mahomes",
      team: "KC",
    },

    points: 26,
    user: "Bijan Mustard",
  },
  {
    player: {
      position: "QB",
      player_id: "4943",
      name: "Sam Darnold",
      team: "SEA",
    },
    points: 24.78,
    user: "Dak to the Future",
  },
  {
    player: {
      position: "TE",
      player_id: "1339",
      name: "Zach Ertz",
      team: "WAS",
    },
    points: 22.2,
    user: "Lamario Kart ",
  },
  {
    player: {
      position: "WR",
      player_id: "8148",
      name: "Jameson Williams",
      team: "DET",
    },
    points: 22,
    user: "Breece's Puffs",
  },
];
export const fakeHighlights = [
  "**Collard Greens** is the hottest team, riding a dominant 5-game win streak and averaging 132 points per game over that span, vaulting to 3rd place.",
  "**Saquondo** leads the league in total points (1646) but just saw a 4-game win streak snapped, opening the door for surging contenders.",
];
export const fakeWaiverMoves = [
  {
    id: 1,
    user: {
      id: "1",
      name: "Just the Tua Us",
      username: "Just the Tua Us",
      avatar: "3fd3d500b13b04926820e10e9306f6ab",
      avatarImg: "../avatars/avatar1.svg",
    },
    adds: "Isaiah Likely",
    week: 1,
    value: 23.3,
    position: "TE",
    player_id: "8131",
    bid: 5,
    status: "complete",
  },
  {
    id: 1,
    user: {
      id: "1",
      name: "Just the Tua Us",
      username: "Just the Tua Us",
      avatar: "3fd3d500b13b04926820e10e9306f6ab",
      avatarImg: "../avatars/avatar1.svg",
    },
    adds: "Ray Davis",
    week: 3,
    value: 35.3,
    position: "RB",
    player_id: "11575",
    bid: 1,
    status: "complete",
  },
  {
    id: 1,
    user: {
      id: "1",
      name: "Just the Tua Us",
      username: "Just the Tua Us",
      avatar: "3fd3d500b13b04926820e10e9306f6ab",
      avatarImg: "../avatars/avatar1.svg",
    },
    adds: "Darnell Mooney",
    week: 7,
    value: 18.4,
    position: "WR",
    player_id: "7090",
    bid: 2,
    status: "complete",
  },
  {
    id: 1,
    user: {
      id: "1",
      name: "Just the Tua Us",
      username: "Just the Tua Us",
      avatar: "3fd3d500b13b04926820e10e9306f6ab",
      avatarImg: "../avatars/avatar1.svg",
    },
    adds: "Kimani Vidal",
    week: 8,
    value: 68.2,
    position: "RB",
    player_id: "11647",
    bid: 1,
    status: "complete",
  },
  {
    id: 1,
    user: {
      id: "1",
      name: "Just the Tua Us",
      username: "Just the Tua Us",
      avatar: "3fd3d500b13b04926820e10e9306f6ab",
      avatarImg: "../avatars/avatar1.svg",
    },
    adds: "CIN Defense",
    week: 10,
    value: 22.4,
    position: "DEF",
    player_id: "100",
    bid: 1,
    status: "complete",
  },
  {
    id: 1,
    user: {
      id: "1",
      name: "Just the Tua Us",
      username: "Just the Tua Us",
      avatar: "3fd3d500b13b04926820e10e9306f6ab",
      avatarImg: "../avatars/avatar1.svg",
    },
    adds: "Juwan Johnson",
    week: 11,
    value: 18.2,
    position: "TE",
    player_id: "7002",
    bid: 3,
    status: "complete",
  },
  {
    id: 1,
    user: {
      id: "1",
      name: "Just the Tua Us",
      username: "Just the Tua Us",
      avatar: "3fd3d500b13b04926820e10e9306f6ab",
      avatarImg: "../avatars/avatar1.svg",
    },
    adds: "Stone Smartt",
    week: 13,
    value: 26,
    position: "TE",
    player_id: "8583",
    bid: 1,
    status: "complete",
  },
  {
    id: 2,
    user: {
      id: "2",
      name: "Bijan Mustard",
      username: "Bijan Mustard",
      avatar: "a77d198f5c82bd93d3da5bd10493f7cd",
      avatarImg: "../avatars/avatar2.svg",
    },
    adds: "Baker Mayfield",
    week: 2,
    value: 10.4,
    position: "QB",
    player_id: "4892",
    bid: 6,
    status: "complete",
  },
  {
    id: 3,
    user: {
      id: "3",
      name: "The Princess McBride",
      username: "The Princess McBride",
      avatar: "8eb8f8bf999945d523f2c4033f70473e",
      avatarImg: "../avatars/avatar3.svg",
    },
    adds: "Jerome Ford",
    week: 9,
    value: 31.1,
    position: "RB",
    player_id: "8143",
    bid: 2,
    status: "complete",
  },
  {
    id: 4,
    user: {
      id: "4",
      name: "Baby Back Gibbs",
      username: "Baby Back Gibbs",
      avatar: "15d7cf259bc30eab8f6120f45f652fb6",
      avatarImg: "../avatars/avatar4.svg",
    },
    adds: "Cam Akers",
    week: 3,
    value: 40.6,
    position: "RB",
    player_id: "6938",
    bid: 3,
    status: "complete",
  },
  {
    id: 5,
    user: {
      id: "5",
      name: "Breece's Puffs",
      username: "Breece's Puffs",
      avatar: "15d7cf259bc30eab8f6120f45f652fb6",
      avatarImg: "../avatars/avatar5.svg",
    },
    adds: "Dalton Schultz",
    week: 3,
    value: 22.6,
    position: "RB",
    player_id: "5001",
    bid: 5,
    status: "complete",
  },
];

export const fakeTrades = [
  {
    team1: {
      user: {
        id: "1",
        name: "Just the Tua Us",
        avatar: "3fd3d500b13b04926820e10e9306f6ab",
        avatarImg: "../avatars/avatar1.svg",
        transactions: 14,
      },
      players: ["J.K. Dobbins"],
      draftPicks: [],
      waiverBudget: [],
      value: [19],
    },
    team2: {
      user: {
        id: "2",
        name: "Bijan Mustard",
        avatar: "a77d198f5c82bd93d3da5bd10493f7cd",
        avatarImg: "../avatars/avatar2.svg",
        transactions: 10,
      },
      players: ["Zack Moss", "Tyler Allgeier"],
      draftPicks: [],
      waiverBudget: [],
      value: [32.8, 41.2],
    },
  },
  {
    team1: {
      user: {
        id: "3",
        name: "The Princess McBride",
        avatar: "8eb8f8bf999945d523f2c4033f70473e",
        avatarImg: "../avatars/avatar3.svg",
        transactions: 25,
      },
      players: ["Justice Hill"],
      draftPicks: [],
      waiverBudget: [],
      value: [38.8],
    },
    team2: {
      user: {
        id: "4",
        name: "Baby Back Gibbs",
        avatar: "15d7cf259bc30eab8f6120f45f652fb6",
        avatarImg: "../avatars/avatar4.svg",
        transactions: 31,
      },
      players: ["Tyjae Spears"],
      draftPicks: [],
      waiverBudget: [],
      value: [34],
    },
  },
  {
    team1: {
      user: {
        id: "4",
        name: "Baby Back Gibbs",
        avatar: "15d7cf259bc30eab8f6120f45f652fb6",
        avatarImg: "../avatars/avatar4.svg",
        transactions: 31,
      },
      players: ["Tank Bigsby"],
      draftPicks: [],
      waiverBudget: [],
      value: [40],
    },
    team2: {
      user: {
        id: "5",
        name: "Breece's Puffs",
        avatar: "15d7cf259bc30eab8f6120f45f652fb6",
        avatarImg: "../avatars/avatar5.svg",
        transactions: 38,
      },
      players: ["Jordan Love"],
      draftPicks: [],
      waiverBudget: [],
      value: [17],
    },
  },
  {
    team1: {
      user: {
        id: "6",
        name: "Saquondo ",
        avatar: "d6ad9a18c52dcdb704399beed5d5b21f",
        avatarImg: "../avatars/avatar6.svg",
        transactions: 29,
      },
      players: ["Justice Hill", "Quentin Johnston", "Jayden Daniels"],
      draftPicks: [],
      waiverBudget: [],
      value: [38.8, 44.4, 11.5],
    },
    team2: {
      user: {
        id: "7",
        name: "Lamario Kart ",
        avatar: "3d8ea1e7289177ddf22dd57e107ee334",
        avatarImg: "../avatars/avatar7.svg",
        transactions: 19,
      },
      players: ["Jalen Hurts", "Tank Dell", "Tyjae Spears"],
      draftPicks: [],
      waiverBudget: [],
      value: [9.7, 37, 34],
    },
  },
  {
    team1: {
      user: {
        id: "8",
        name: "Ja’Marr the Merrier",
        avatar: "4f4090e5e9c3941414db40a871e3e909",
        avatarImg: "../avatars/avatar8.svg",
        transactions: 40,
      },
      players: ["Aaron Jones", "Cam Akers", "Najee Harris", "Cedric Tillman"],
      draftPicks: [],
      waiverBudget: [],
      value: [17.3, 44.5, 25.7, 49.6],
    },
    team2: {
      user: {
        id: "9",
        name: "Dak to the Future",
        avatar: "b3338675f635c2c1f42b469621d38ec6",
        avatarImg: "../avatars/avatar9.svg",
        transactions: 33,
      },
      players: ["Alvin Kamara", "Bo Nix"],
      draftPicks: [],
      waiverBudget: [],
      value: [16.3, 15],
    },
  },
  {
    team1: {
      user: {
        id: "9",
        name: "Dak to the Future",
        avatar: "b3338675f635c2c1f42b469621d38ec6",
        avatarImg: "../avatars/avatar9.svg",
        transactions: 33,
      },
      players: ["Nick Chubb", "Courtland Sutton", "James Cook", "Bucky Irving"],
      draftPicks: [],
      waiverBudget: [],
      value: [30.5, 27.4, 13.4, 15.2],
    },
    team2: {
      user: {
        id: "10",
        name: "LaPorta Potty",
        avatar: "81d984f3556782876d25195356b0ab58",
        avatarImg: "../avatars/avatar10.svg",
        transactions: 42,
      },
      players: [
        "Javonte Williams",
        "Tyler Allgeier",
        "Bijan Robinson",
        "Quentin Johnston",
      ],
      draftPicks: [],
      waiverBudget: [],
      value: [48.6, 46.2, 7.2, 53],
    },
  },
];

export const fakeTransactions = [
  { name: "Waiver Claims", data: [1, 6, 3, 3, 7, 6, 4, 3, 10, 9] },
  { name: "Free Agents", data: [4, 2, 6, 7, 3, 6, 9, 13, 7, 10] },
  { name: "Trades", data: [0, 0, 0, 0, 0, 0, 0, 1, 1, 0] },
];

export const fakeUsers = [
  {
    id: "1",
    name: "Just the Tua Us",
    avatar: "3fd3d500b13b04926820e10e9306f6ab",
    avatarImg: "../avatars/avatar1.svg",
    transactions: 14,
    username: "Just the Tua Us",
  },
  {
    id: "2",
    name: "Bijan Mustard",
    username: "Bijan Mustard",
    avatar: "a77d198f5c82bd93d3da5bd10493f7cd",
    avatarImg: "../avatars/avatar2.svg",
    transactions: 10,
  },
  {
    id: "3",
    name: "The Princess McBride",
    username: "The Princess McBride",
    avatar: "8eb8f8bf999945d523f2c4033f70473e",
    avatarImg: "../avatars/avatar3.svg",
    transactions: 25,
  },
  {
    id: "4",
    name: "Baby Back Gibbs",
    username: "Baby Back Gibbs",
    avatar: "15d7cf259bc30eab8f6120f45f652fb6",
    avatarImg: "../avatars/avatar4.svg",
    transactions: 31,
  },
  {
    id: "5",
    name: "Breece's Puffs",
    username: "Breece's Puffs",
    avatar: "15d7cf259bc30eab8f6120f45f652fb6",
    avatarImg: "../avatars/avatar5.svg",
    transactions: 38,
  },
  {
    id: "6",
    name: "Saquondo",
    username: "Saquondo",
    avatar: "d6ad9a18c52dcdb704399beed5d5b21f",
    avatarImg: "../avatars/avatar6.svg",
    transactions: 29,
  },
  {
    id: "7",
    name: "Lamario Kart",
    username: "Lamario Kart",
    avatar: "3d8ea1e7289177ddf22dd57e107ee334",
    avatarImg: "../avatars/avatar7.svg",
    transactions: 19,
  },
  {
    id: "8",
    name: "Ja’Marr the Merrier",
    username: "Ja’Marr the Merrier",
    avatar: "4f4090e5e9c3941414db40a871e3e909",
    avatarImg: "../avatars/avatar8.svg",
    transactions: 40,
  },
  {
    id: "9",
    name: "Dak to the Future",
    username: "Dak to the Future",
    avatar: "b3338675f635c2c1f42b469621d38ec6",
    avatarImg: "../avatars/avatar9.svg",
    transactions: 33,
  },
  {
    id: "10",
    name: "LaPorta Potty",
    username: "LaPorta Potty",
    avatar: "81d984f3556782876d25195356b0ab58",
    avatarImg: "../avatars/avatar10.svg",
    transactions: 42,
  },
];
export const fakeRosters = [
  {
    id: "1",
    pointsFor: 1379,
    pointsAgainst: 1509,
    potentialPoints: 1500,
    wins: 5,
    losses: 9,
    ties: 0,
    rosterId: 1,
    managerEfficiency: 0.914,
    recordByWeek: "WWLWLLLLWLWLLL",
  },
  {
    id: "2",
    pointsFor: 1383,
    pointsAgainst: 1412,
    potentialPoints: 1482,
    wins: 7,
    losses: 7,
    ties: 0,
    rosterId: 2,
    managerEfficiency: 0.953,
    recordByWeek: "WLWLLWLWWLWWLL",
  },
  {
    id: "3",
    pointsFor: 1549,
    potentialPoints: 1690,
    pointsAgainst: 1501,
    wins: 9,
    losses: 5,
    ties: 0,
    rosterId: 3,
    managerEfficiency: 0.916,
    recordByWeek: "WLWLWLWWLLWWWW",
  },
  {
    id: "4",
    pointsFor: 1553,
    pointsAgainst: 1433,
    potentialPoints: 1807,
    wins: 8,
    losses: 6,
    ties: 0,
    rosterId: 4,
    managerEfficiency: 0.859,
    recordByWeek: "WLWLWLWWLWLWLW",
  },
  {
    id: "5",
    pointsFor: 1599,
    pointsAgainst: 1535,
    potentialPoints: 1790,
    wins: 8,
    losses: 6,
    ties: 0,
    rosterId: 5,
    managerEfficiency: 0.893,
    recordByWeek: "WLLWWLLWWLLWWW",
  },
  {
    id: "6",
    pointsFor: 1646,
    potentialPoints: 1796,
    pointsAgainst: 1502,
    wins: 9,
    losses: 5,
    ties: 0,
    rosterId: 6,
    managerEfficiency: 0.916,
    recordByWeek: "LWWWLWWWLLWWLW",
  },
  {
    id: "7",
    pointsFor: 1475,
    potentialPoints: 1725,
    pointsAgainst: 1408,
    wins: 6,
    losses: 8,
    ties: 0,
    rosterId: 7,
    managerEfficiency: 0.855,
    recordByWeek: "LWLWWLWLWWLLLL",
  },
  {
    id: "8",
    pointsFor: 1567,
    potentialPoints: 1787,
    pointsAgainst: 1501,
    wins: 8,
    losses: 6,
    ties: 0,
    rosterId: 8,
    managerEfficiency: 0.876,
    recordByWeek: "LWWLLWLLLWWWWW",
  },
  {
    id: "9",
    pointsFor: 1402,
    potentialPoints: 1643,
    pointsAgainst: 1543,
    wins: 5,
    losses: 9,
    ties: 0,
    rosterId: 9,
    managerEfficiency: 0.853,
    recordByWeek: "LWLWLLWLLLLWWL",
  },
  {
    id: "10",
    pointsFor: 1478,
    potentialPoints: 1697,
    pointsAgainst: 1470,
    wins: 7,
    losses: 7,
    ties: 0,
    rosterId: 10,
    managerEfficiency: 0.87,
    recordByWeek: "LLWLLWWLWWWLWL",
  },
];
export const fakePoints = [
  {
    rosterId: 1,
    points: [
      96.26, 103.9, 76.3, 91.08, 133.34, 114.08, 92.26, 111.02, 63.34, 84.72,
      121.1, 78.18, 101.68, 82.64,
    ],
    playoffPoints: [94.31, 99.75, 103.21],
    matchups: [2, 3, 4, 2, 2, 1, 3, 5, 1, 3, 2, 2, 4, 2],
    starters: [],
    starterPoints: [],
    benchPlayers: [],
    benchPoints: [],
  },
  {
    rosterId: 2,
    points: [
      108.78, 97.72, 145.82, 80.42, 89.14, 92.92, 74.88, 120.74, 120.56, 92.92,
      67.44, 101.46, 109.26, 82.42,
    ],
    playoffPoints: [88.33, 104.13, 110.87],
    matchups: [1, 1, 5, 2, 3, 5, 4, 1, 5, 2, 4, 3, 2, 1],
    starters: [],
    starterPoints: [],
    benchPlayers: [],
    benchPoints: [],
  },
  {
    rosterId: 3,
    points: [
      129.14, 95, 125.88, 70.72, 130.94, 88.14, 123.86, 127.2, 109.2, 100.32,
      104.28, 128.62, 126, 124.48,
    ],
    playoffPoints: [101.98, 110.71, 98.31],
    matchups: [3, 4, 2, 3, 1, 4, 3, 5, 3, 2, 5, 2, 5, 4],
    starters: [],
    starterPoints: [],
    benchPlayers: [],
    benchPoints: [],
  },
  {
    rosterId: 4,
    points: [
      104.04, 89.66, 159.92, 105.28, 102.92, 153.98, 102.64, 115.06, 77.12,
      130.76, 103.5, 126.72, 87.2, 95,
    ],
    playoffPoints: [103.53, 124.68, 100.48],
    matchups: [4, 5, 3, 5, 5, 4, 1, 4, 3, 5, 1, 1, 1, 1],
    starters: [],
    starterPoints: [],
    benchPlayers: [],
    benchPoints: [],
  },
  {
    rosterId: 5,
    points: [
      90.74, 97.14, 113.06, 148.9, 162.78, 73.82, 90.64, 123.4, 144.1, 101.94,
      86.04, 147.46, 125.08, 94.82,
    ],
    playoffPoints: [111.39, 120.01, 89.68],
    matchups: [5, 2, 1, 1, 4, 3, 2, 3, 5, 4, 5, 3, 1, 3],
    starters: [],
    starterPoints: [],
    benchPlayers: [],
    benchPoints: [],
  },
  {
    rosterId: 6,
    points: [
      114.54, 126.36, 113.92, 151.7, 115.26, 99.36, 105.2, 120.26, 123.42,
      127.18, 131.9, 142.56, 99.28, 129.62,
    ],
    playoffPoints: [99.58, 131.79, 101.39],
    matchups: [3, 1, 1, 4, 2, 3, 5, 2, 2, 1, 4, 4, 4, 5],
    starters: [],
    starterPoints: [],
    benchPlayers: [],
    benchPoints: [],
  },
  {
    rosterId: 7,
    points: [
      97.36, 116.08, 126.58, 125.54, 90.04, 97.42, 104.88, 91.38, 104.68, 96.62,
      83.36, 136.08, 115, 90.44,
    ],
    playoffPoints: [97.32, 93.11, 105.11],
    matchups: [4, 2, 5, 5, 3, 1, 1, 1, 4, 3, 3, 5, 3, 3],
    starters: [],
    starterPoints: [],
    benchPlayers: [],
    benchPoints: [],
  },
  {
    rosterId: 8,
    points: [
      89.5, 145.42, 131.78, 86.26, 86.12, 112.2, 90.76, 101.26, 86.78, 140.92,
      104, 139.2, 128.62, 90.04,
    ],
    playoffPoints: [116.21, 108.19, 98.14],
    matchups: [2, 4, 4, 4, 1, 5, 5, 3, 2, 1, 1, 5, 3, 2],
    starters: [],
    starterPoints: [],
    benchPlayers: [],
    benchPoints: [],
  },
  {
    rosterId: 9,
    points: [
      89.94, 111.94, 98.68, 108.96, 97.36, 93.14, 104.16, 98.38, 94.58, 128.9,
      114.78, 92.16, 93.62, 76.3,
    ],
    playoffPoints: [95.97, 112.49, 118.24],
    matchups: [1, 5, 2, 3, 5, 2, 2, 2, 4, 5, 2, 1, 5, 4],
    starters: [],
    starterPoints: [],
    benchPlayers: [],
    benchPoints: [],
  },
  {
    rosterId: 10,
    points: [
      63.68, 78.88, 115.16, 108.64, 102.28, 100.5, 97.4, 149.92, 99.02, 116.28,
      108.64, 82.4, 131.96, 123.26,
    ],
    playoffPoints: [100.55, 107.57, 117.91],
    matchups: [5, 3, 3, 1, 4, 2, 4, 4, 1, 4, 3, 4, 2, 5],
    starters: [],
    starterPoints: [],
    benchPlayers: [],
    benchPoints: [],
  },
];

export const fakeWinnersBracket = [
  {
    t2: 4,
    t1: 10,
    w: 4,
    l: 10,
    r: 1,
    m: 1,
  },
  {
    t2: 5,
    t1: 3,
    w: 5,
    l: 3,
    r: 1,
    m: 2,
  },
  {
    t2_from: {
      w: 1,
    },
    t2: 4,
    t1: 8,
    w: 4,
    l: 8,
    r: 2,
    m: 3,
  },
  {
    t2_from: {
      w: 2,
    },
    t2: 5,
    t1: 6,
    w: 6,
    l: 5,
    r: 2,
    m: 4,
  },
  {
    t1_from: {
      l: 1,
    },
    t2_from: {
      l: 2,
    },
    t2: 3,
    t1: 10,
    w: 3,
    l: 10,
    r: 2,
    p: 5,
    m: 5,
  },
  {
    t1_from: {
      w: 3,
    },
    t2_from: {
      w: 4,
    },
    t2: 6,
    t1: 4,
    w: 6,
    l: 4,
    r: 3,
    p: 1,
    m: 6,
  },
  {
    t1_from: {
      l: 3,
    },
    t2_from: {
      l: 4,
    },
    t2: 5,
    t1: 8,
    w: 8,
    l: 5,
    r: 3,
    p: 3,
    m: 7,
  },
];

export const fakeLosersBracket = [
  {
    t2: 1,
    t1: 2,
    w: 2,
    l: 1,
    r: 1,
    m: 1,
  },
  {
    t2: 7,
    t1: 9,
    w: 9,
    l: 7,
    r: 1,
    m: 2,
  },
  {
    t1_from: {
      w: 1,
    },
    t2_from: {
      w: 2,
    },
    t2: 9,
    t1: 2,
    w: 2,
    l: 9,
    r: 2,
    m: 3,
    p: 1,
  },
  {
    t1_from: {
      l: 1,
    },
    t2_from: {
      l: 2,
    },
    t2: 7,
    t1: 1,
    w: 7,
    l: 1,
    r: 2,
    m: 4,
    p: 3,
  },
];

export const fakePlayoffData = [
  {
    name: "Saquondo",
    username: "",
    projectedWinsTotal: 0,
    placement: [100, 0, 0, 0, 0, 0],
  },
  {
    name: "Breece's Puffs",
    username: "",
    projectedWinsTotal: 0,
    placement: [0, 0, 100, 0, 0, 0],
  },
  {
    name: "Baby Back Gibbs",
    username: "",
    projectedWinsTotal: 0,
    placement: [0, 0, 0, 100, 0, 0],
  },
  {
    name: "Ja’Marr the Merrier",
    username: "",
    projectedWinsTotal: 0,
    placement: [0, 100, 0, 0, 0, 0],
  },
  {
    name: "The Princess McBride",
    username: "",
    projectedWinsTotal: 0,
    placement: [0, 0, 0, 0, 100, 0],
  },
  {
    name: "LaPorta Potty",
    username: "",
    projectedWinsTotal: 0,
    placement: [0, 0, 0, 0, 0, 100],
  },
  {
    name: "Lamario Kart ",
    username: "",
    projectedWinsTotal: 0,
    placement: [0, 0, 0, 0, 0, 0],
  },
  {
    name: "Bijan Mustard",
    username: "",
    projectedWinsTotal: 0,
    placement: [0, 0, 0, 0, 0, 0],
  },
  {
    name: "Dak to the Future",
    username: "",
    projectedWinsTotal: 0,
    placement: [0, 0, 0, 0, 0, 0],
  },
  {
    name: "Just the Tua Us",
    username: "",
    projectedWinsTotal: 0,
    placement: [0, 0, 0, 0, 0, 0],
  },
];

export const fakeProjectionData = [
  {
    name: "Saquondo ",
    data: [
      { position: "RB", projection: 482 },
      { position: "WR", projection: 369 },
      { projection: 288, position: "QB" },
      { projection: 74, position: "TE" },
      { projection: 99, position: "K" },
      { projection: 88, position: "DEF" },
    ],
    total: 1400,
  },
  {
    name: "Breece's Puffs",
    data: [
      { position: "RB", projection: 410 },
      { position: "WR", projection: 427 },
      { projection: 254, position: "QB" },
      { projection: 81, position: "TE" },
      { projection: 115, position: "K" },
      { projection: 88, position: "DEF" },
    ],
    total: 1375,
  },
  {
    name: "Baby Back Gibbs",
    data: [
      { position: "RB", projection: 376 },
      { position: "WR", projection: 336 },
      { projection: 315, position: "QB" },
      { projection: 77, position: "TE" },
      { projection: 124, position: "K" },
      { projection: 97, position: "DEF" },
    ],
    total: 1325,
  },
  {
    name: "Ja’Marr the Merrier",
    data: [
      { position: "RB", projection: 412 },
      { position: "WR", projection: 351 },
      { projection: 298, position: "QB" },
      { projection: 62, position: "TE" },
      { projection: 114, position: "K" },
      { projection: 85, position: "DEF" },
    ],
    total: 1322,
  },
  {
    name: "The Princess McBride",
    data: [
      { position: "RB", projection: 390 },
      { position: "WR", projection: 354 },
      { projection: 297, position: "QB" },
      { projection: 46, position: "TE" },
      { projection: 120, position: "K" },
      { projection: 102, position: "DEF" },
    ],
    total: 1309,
  },
  {
    name: "LaPorta Potty",
    data: [
      { position: "RB", projection: 359 },
      { position: "WR", projection: 342 },
      { projection: 280, position: "QB" },
      { projection: 71, position: "TE" },
      { projection: 121, position: "K" },
      { projection: 90, position: "DEF" },
    ],
    total: 1263,
  },
  {
    name: "Lamario Kart ",
    data: [
      { position: "RB", projection: 422 },
      { position: "WR", projection: 331 },
      { projection: 240, position: "QB" },
      { projection: 69, position: "TE" },
      { projection: 98, position: "K" },
      { projection: 93, position: "DEF" },
    ],
    total: 1253,
  },
  {
    name: "Bijan Mustard",
    data: [
      { position: "RB", projection: 374 },
      { position: "WR", projection: 335 },
      { projection: 264, position: "QB" },
      { projection: 55, position: "TE" },
      { projection: 111, position: "K" },
      { projection: 100, position: "DEF" },
    ],
    total: 1239,
  },
  {
    name: "Dak to the Future",
    data: [
      { position: "RB", projection: 400 },
      { position: "WR", projection: 330 },
      { projection: 259, position: "QB" },
      { projection: 90, position: "TE" },
      { projection: 83, position: "K" },
      { projection: 74, position: "DEF" },
    ],
    total: 1230,
  },
  {
    name: "Just the Tua Us",
    data: [
      { position: "RB", projection: 247 },
      { position: "WR", projection: 344 },
      { projection: 251, position: "QB" },
      { projection: 97, position: "TE" },
      { projection: 109, position: "K" },
      { projection: 88, position: "DEF" },
    ],
    total: 1136,
  },
];

export const fakePosts = [
  {
    uri: "at://did:plc:lbe3b7ce6n7oa6cbl5jwoifo/app.bsky.feed.post/3m4jif547uj2o",
    cid: "bafyreigasc76roxnvlwpbvyhd3jsuqpu4utj5nedoylou4tkgmwm7xw6zu",
    author: {
      did: "did:plc:lbe3b7ce6n7oa6cbl5jwoifo",
      handle: "rotoworld-fb.bsky.social",
      displayName: "Rotoworld Football",
      avatar:
        "https://cdn.bsky.app/img/avatar/plain/did:plc:lbe3b7ce6n7oa6cbl5jwoifo/bafkreiewb24yhxcfgoxb6wzu2tctlb2y7tkmo4cygc6hszaljiqhhheode@jpeg",
      associated: { activitySubscription: { allowSubscriptions: "followers" } },
      viewer: { muted: false, blockedBy: false },
      labels: [],
      createdAt: "2024-12-02T17:30:41.845Z",
    },
    record: {
      $type: "app.bsky.feed.post",
      createdAt: "2025-10-31T22:07:07Z",
      embed: {
        $type: "app.bsky.embed.external",
        external: {
          description:
            "Jaguars WR Brian Thomas Jr. (shoulder) was removed from the injury report and will play in Week 9 against the Raiders.",
          thumb: {
            $type: "blob",
            ref: {
              $link:
                "bafkreigaejnaxtnuna5psfo62cx2hx6cokv4rkljfc7ub6zxx36ds4kecu",
            },
            mimeType: "image/jpeg",
            size: 93152,
          },
          title: "Brian Thomas Jr. (shoulder) logs 3 LPs, will play",
          uri: "http://dlvr.it/TP0XPB",
        },
      },
      text: "Brian Thomas Jr. (shoulder) logs 3 LPs, will play",
    },
    embed: {
      $type: "app.bsky.embed.external#view",
      external: {
        uri: "http://dlvr.it/TP0XPB",
        title: "Brian Thomas Jr. (shoulder) logs 3 LPs, will play",
        description:
          "Jaguars WR Brian Thomas Jr. (shoulder) was removed from the injury report and will play in Week 9 against the Raiders.",
        thumb:
          "https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:lbe3b7ce6n7oa6cbl5jwoifo/bafkreigaejnaxtnuna5psfo62cx2hx6cokv4rkljfc7ub6zxx36ds4kecu@jpeg",
      },
    },
    bookmarkCount: 0,
    replyCount: 0,
    repostCount: 1,
    likeCount: 6,
    quoteCount: 0,
    indexedAt: "2025-10-31T22:07:08.665Z",
    viewer: { bookmarked: false, threadMuted: false, embeddingDisabled: false },
    labels: [],
  },
  {
    uri: "at://did:plc:lbe3b7ce6n7oa6cbl5jwoifo/app.bsky.feed.post/3m4jhv5mier2d",
    cid: "bafyreih4i4elly5r2wlgdllnun6niuoatqmecatkmhqn3hnrkxwziplsxu",
    author: {
      did: "did:plc:lbe3b7ce6n7oa6cbl5jwoifo",
      handle: "rotoworld-fb.bsky.social",
      displayName: "Rotoworld Football",
      avatar:
        "https://cdn.bsky.app/img/avatar/plain/did:plc:lbe3b7ce6n7oa6cbl5jwoifo/bafkreiewb24yhxcfgoxb6wzu2tctlb2y7tkmo4cygc6hszaljiqhhheode@jpeg",
      associated: { activitySubscription: { allowSubscriptions: "followers" } },
      viewer: { muted: false, blockedBy: false },
      labels: [],
      createdAt: "2024-12-02T17:30:41.845Z",
    },
    record: {
      $type: "app.bsky.feed.post",
      createdAt: "2025-10-31T21:58:11Z",
      embed: {
        $type: "app.bsky.embed.external",
        external: {
          description:
            "Texans RB Woody Marks (calf) was removed from the injury report and will play in Week 9 against the Broncos.",
          thumb: {
            $type: "blob",
            ref: {
              $link:
                "bafkreicdgcj5dgog5wuv5cowpw3uajfcvb5p3cfbk3wubr4qlbieenff3m",
            },
            mimeType: "image/jpeg",
            size: 91576,
          },
          title: "Woody Marks (calf) good to go after Thursday LP",
          uri: "http://dlvr.it/TP0X3k",
        },
      },
      text: "Woody Marks (calf) good to go after Thursday LP",
    },
    embed: {
      $type: "app.bsky.embed.external#view",
      external: {
        uri: "http://dlvr.it/TP0X3k",
        title: "Woody Marks (calf) good to go after Thursday LP",
        description:
          "Texans RB Woody Marks (calf) was removed from the injury report and will play in Week 9 against the Broncos.",
        thumb:
          "https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:lbe3b7ce6n7oa6cbl5jwoifo/bafkreicdgcj5dgog5wuv5cowpw3uajfcvb5p3cfbk3wubr4qlbieenff3m@jpeg",
      },
    },
    bookmarkCount: 0,
    replyCount: 0,
    repostCount: 0,
    likeCount: 6,
    quoteCount: 0,
    indexedAt: "2025-10-31T21:58:12.565Z",
    viewer: { bookmarked: false, threadMuted: false, embeddingDisabled: false },
    labels: [],
  },
];

export const fakeStartSit = [
  {
    id: 1,
    players: [
      {
        position: "QB",
        player_id: "421",
        name: "Matthew Stafford",
        team: "LAR",
        projection: { stats: 19.55, opponent: "SF", away: true },
        stats: {
          points: [26.84, "DNP", 27.38, 9.34, 25.56, 27.4, 14.84],
          ranks: [8, "DNP", 4, 26, 8, 2, 14],
          stats: [
            {
              rec: "0",
              rec_yd: "0",
              rush_att: 4,
              rush_yd: -4,
              rush_td: "0",
              pass_td: 4,
              rec_td: "0",
              pass_yd: 281,
              snaps: 80,
              team_snaps: 80,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {},
            {
              rec: "0",
              rec_yd: "0",
              rush_att: 2,
              rush_yd: 1,
              rush_td: "0",
              pass_td: 5,
              rec_td: "0",
              pass_yd: 182,
              snaps: 67,
              team_snaps: 70,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: "0",
              rec_yd: "0",
              rush_att: 4,
              rush_yd: 1,
              rush_td: "0",
              pass_td: 1,
              rec_td: "0",
              pass_yd: 181,
              snaps: 53,
              team_snaps: 53,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: "0",
              rec_yd: "0",
              rush_att: 1,
              rush_yd: "0",
              rush_td: "0",
              pass_td: 3,
              rec_td: "0",
              pass_yd: 389,
              snaps: 68,
              team_snaps: 68,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: "0",
              rec_yd: "0",
              rush_att: 4,
              rush_yd: 4,
              rush_td: "0",
              pass_td: 3,
              rec_td: "0",
              pass_yd: 375,
              snaps: 75,
              team_snaps: 75,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: "0",
              rec_yd: "0",
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: 2,
              rec_td: "0",
              pass_yd: 196,
              snaps: 66,
              team_snaps: 66,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
          ],
        },
      },
      {
        position: "RB",
        player_id: "4035",
        name: "Alvin Kamara",
        team: "NO",
        projection: { stats: 9.8, opponent: "CAR", away: true },
        stats: {
          points: [0.2, 5.5, 4.4, 10.1, 7.5, 9.2, 6.1],
          ranks: [65, 35, 40, 16, 29, 31, 37],
          stats: [
            {
              rec: 1,
              rec_yd: 3,
              rush_att: 6,
              rush_yd: 14,
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 24,
              team_snaps: 41,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 2,
              rec_yd: 24,
              rush_att: 6,
              rush_yd: 21,
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 37,
              team_snaps: 72,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 3,
              rec_yd: 1,
              rush_att: 11,
              rush_yd: 28,
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 47,
              team_snaps: 56,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 5,
              rec_yd: 45,
              rush_att: 10,
              rush_yd: 31,
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 35,
              team_snaps: 56,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 4,
              rec_yd: 28,
              rush_att: 8,
              rush_yd: 27,
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 37,
              team_snaps: 66,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 4,
              rec_yd: 2,
              rush_att: 15,
              rush_yd: 70,
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 49,
              team_snaps: 67,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 1,
              rec_yd: 14,
              rush_att: 18,
              rush_yd: 42,
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 54,
              team_snaps: 73,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
          ],
        },
      },
      {
        position: "RB",
        player_id: "12534",
        name: "Kyle Monangai",
        team: "CHI",
        projection: { stats: 8.47, opponent: "NYG", away: false },
        stats: {
          points: [21.3, 2.4, 16.4, 4.9, "DNP", 1.8, 2.5],
          ranks: [3, 51, 12, 37, "DNP", 58, 60],
          stats: [
            {
              rec: 3,
              rec_yd: 22,
              rush_att: 26,
              rush_yd: 176,
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 59,
              team_snaps: 80,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: "0",
              rec_yd: "0",
              rush_att: 7,
              rush_yd: 24,
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 29,
              team_snaps: 63,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 2,
              rec_yd: 13,
              rush_att: 13,
              rush_yd: 81,
              rush_td: 1,
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 31,
              team_snaps: 69,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 1,
              rec_yd: 25,
              rush_att: 5,
              rush_yd: 19,
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 22,
              team_snaps: 64,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {},
            {
              rec: "0",
              rec_yd: "0",
              rush_att: 4,
              rush_yd: 18,
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 19,
              team_snaps: 68,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 1,
              rec_yd: 4,
              rush_att: 6,
              rush_yd: 16,
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 17,
              team_snaps: 59,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
          ],
        },
      },
      {
        position: "WR",
        player_id: "7569",
        name: "Nico Collins",
        team: "HOU",
        projection: { stats: 13.12, opponent: "JAX", away: false },
        stats: {
          points: [11, "DNP", 4.7, "DNP", 14, 9.9, 18.4],
          ranks: [28, "DNP", 59, "DNP", 17, 27, 5],
          stats: [
            {
              rec: 7,
              rec_yd: 75,
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 58,
              team_snaps: 73,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {},
            {
              rec: 4,
              rec_yd: 27,
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 39,
              team_snaps: 76,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {},
            {
              rec: 4,
              rec_yd: 52,
              rush_att: 1,
              rush_yd: 8,
              rush_td: "0",
              pass_td: "0",
              rec_td: 1,
              pass_yd: "0",
              snaps: 40,
              team_snaps: 70,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 4,
              rec_yd: 79,
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 61,
              team_snaps: 71,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 8,
              rec_yd: 104,
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: 1,
              pass_yd: "0",
              snaps: 54,
              team_snaps: 63,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
          ],
        },
      },
      {
        position: "WR",
        player_id: "8112",
        name: "Drake London",
        team: "ATL",
        projection: { stats: 13.61, opponent: "IND", away: true },
        stats: {
          points: [34.3, "DNP", 6.2, 26.8, "DNP", 21, 8],
          ranks: [1, "DNP", 46, 2, "DNP", 6, 38],
          stats: [
            {
              rec: 9,
              rec_yd: 118,
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: 3,
              pass_yd: "0",
              snaps: 55,
              team_snaps: 56,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {},
            {
              rec: 4,
              rec_yd: 42,
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 64,
              team_snaps: 65,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 10,
              rec_yd: 158,
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: 1,
              pass_yd: "0",
              snaps: 68,
              team_snaps: 70,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {},
            {
              rec: 8,
              rec_yd: 110,
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: 1,
              pass_yd: "0",
              snaps: 55,
              team_snaps: 65,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 5,
              rec_yd: 55,
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 57,
              team_snaps: 66,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
          ],
        },
      },
      {
        position: "TE",
        player_id: "1339",
        name: "Zach Ertz",
        team: "WAS",
        projection: { stats: 8.05, opponent: "DET", away: false },
        stats: {
          points: [6.6, 3.6, 11.2, 13.3, "0", 5.1, 5.3],
          ranks: [22, 24, 11, 6, 999, 26, 24],
          stats: [
            {
              rec: 4,
              rec_yd: 46,
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 41,
              team_snaps: 65,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 4,
              rec_yd: 16,
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 33,
              team_snaps: 53,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 3,
              rec_yd: 37,
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: 1,
              pass_yd: "0",
              snaps: 45,
              team_snaps: 67,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 6,
              rec_yd: 43,
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: 1,
              pass_yd: "0",
              snaps: 39,
              team_snaps: 65,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: "0",
              rec_yd: "0",
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 31,
              team_snaps: 59,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 2,
              rec_yd: 21,
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 35,
              team_snaps: 57,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
            {
              rec: 3,
              rec_yd: 38,
              rush_att: "0",
              rush_yd: "0",
              rush_td: "0",
              pass_td: "0",
              rec_td: "0",
              pass_yd: "0",
              snaps: 30,
              team_snaps: 58,
              fgm: "0",
              fga: "0",
              xpm: "0",
              xpa: "0",
              sack: "0",
              int: "0",
              ff: "0",
              pts_allow: "0",
              yds_allow: "0",
            },
          ],
        },
      },
    ],
  },
];

export const fakeManagerProfiles = [
  {
    userId: "6",
    displayName: "Saquondo",
    avatarImg: "../avatars/avatar6.svg",
    seasons: 3,
    titles: 0,
    totalWins: 27,
    totalLosses: 15,
    totalTies: 0,
    totalPointsFor: 4938,
    totalPointsAgainst: 5847,
    totalTrades: 1,
    tradeValueGained: -9.200000000000003,
    totalWaivers: 183,
    averageEfficiency: 0.916,
    playoffAppearances: 2,
    averagePointsPerSeason: 1646,
    averageTradesPerSeason: 0.25,
    averageWaiversPerSeason: 45.75,
    winRate: 0.6428,
    weeklyScoreStdDev: 18.958548818573867,
    averageDraftPickRank: null,
  },
];

export const fakeProfileText =
  "Saquondo has been the league’s model of sustained menace, pairing the best scoring profile with a championship to back it up. The draft room clearly loves this manager, and the league-wide top draft ability ranking shows the foundation of the run is not luck or waiver scraping. They also stay active on waivers and turn that work into real production, even if the trade market has been more decorative than dangerous. The only real knock is that opponents have had chances to hang around, but when you finish first in points and first in hardware, that is a very polished problem to have.";
