export const fakePlayerRankings = {
  K: [
    {
      rank: 1,
      points: 188,
      ppg: 11.058823529411764,
      firstName: "Chris",
      lastName: "Boswell",
      position: "K",
      team: "K",
      id: "1945",
      gp: 17,
      overallRank: 87,
    },
    {
      rank: 2,
      points: 171,
      ppg: 10.6875,
      firstName: "Brandon",
      lastName: "Aubrey",
      position: "K",
      team: "K",
      id: "11533",
      gp: 17,
      overallRank: 88,
    },
    {
      rank: 3,
      points: 160,
      ppg: 10,
      firstName: "Ka'imi",
      lastName: "Fairbairn",
      position: "K",
      team: "K",
      id: "3451",
      gp: 17,
      overallRank: 90,
    },
    {
      rank: 4,
      points: 159,
      ppg: 9.9375,
      firstName: "Cameron",
      lastName: "Dicker",
      position: "K",
      team: "K",
      id: "8259",
      gp: 17,
      overallRank: 98,
    },
    {
      rank: 5,
      points: 152,
      ppg: 9.5,
      firstName: "Jason",
      lastName: "Sanders",
      position: "K",
      team: "K",
      id: "5119",
      gp: 17,
      overallRank: 116,
    },
  ],
  QB: [
    {
      rank: 1,
      points: 434.38,
      ppg: 25.551764705882352,
      firstName: "Lamar",
      lastName: "Jackson",
      position: "QB",
      team: "QB",
      id: "4881",
      gp: 17,
      overallRank: 1,
    },
    {
      rank: 2,
      points: 385.04,
      ppg: 24.065,
      firstName: "Josh",
      lastName: "Allen",
      position: "QB",
      team: "QB",
      id: "4984",
      gp: 17,
      overallRank: 2,
    },
    {
      rank: 3,
      points: 381.82,
      ppg: 22.46,
      firstName: "Joe",
      lastName: "Burrow",
      position: "QB",
      team: "QB",
      id: "6770",
      gp: 17,
      overallRank: 3,
    },
    {
      rank: 4,
      points: 360.6,
      ppg: 22.5375,
      firstName: "Jayden",
      lastName: "Daniels",
      position: "QB",
      team: "QB",
      id: "11566",
      gp: 17,
      overallRank: 4,
    },
    {
      rank: 5,
      points: 359.16,
      ppg: 22.4475,
      firstName: "Baker",
      lastName: "Mayfield",
      position: "QB",
      team: "QB",
      id: "4892",
      gp: 17,
      overallRank: 5,
    },
  ],
  WR: [
    {
      rank: 1,
      points: 339.5,
      ppg: 19.970588235294116,
      firstName: "Ja'Marr",
      lastName: "Chase",
      position: "WR",
      team: "WR",
      id: "7564",
      gp: 17,
      overallRank: 6,
    },
    {
      rank: 2,
      points: 259.08,
      ppg: 16.1925,
      firstName: "Justin",
      lastName: "Jefferson",
      position: "WR",
      team: "WR",
      id: "6794",
      gp: 17,
      overallRank: 22,
    },
    {
      rank: 3,
      points: 247.98,
      ppg: 15.49875,
      firstName: "Amon-Ra",
      lastName: "St. Brown",
      position: "WR",
      team: "WR",
      id: "7547",
      gp: 17,
      overallRank: 25,
    },
    {
      rank: 4,
      points: 226.7,
      ppg: 14.16875,
      firstName: "Brian",
      lastName: "Thomas",
      position: "WR",
      team: "WR",
      id: "11631",
      gp: 17,
      overallRank: 29,
    },
    {
      rank: 5,
      points: 212.9,
      ppg: 14.193333333333333,
      firstName: "CeeDee",
      lastName: "Lamb",
      position: "WR",
      team: "WR",
      id: "6786",
      gp: 17,
      overallRank: 34,
    },
  ],
  TE: [
    {
      rank: 1,
      points: 193.9,
      ppg: 13.85,
      firstName: "George",
      lastName: "Kittle",
      position: "TE",
      team: "TE",
      id: "4217",
      gp: 17,
      overallRank: 45,
    },
    {
      rank: 2,
      points: 193.7,
      ppg: 12.10625,
      firstName: "Brock",
      lastName: "Bowers",
      position: "TE",
      team: "TE",
      id: "11604",
      gp: 17,
      overallRank: 54,
    },
    {
      rank: 3,
      points: 178.3,
      ppg: 11.886666666666667,
      firstName: "Trey",
      lastName: "McBride",
      position: "TE",
      team: "TE",
      id: "8130",
      gp: 17,
      overallRank: 56,
    },
    {
      rank: 4,
      points: 164.2,
      ppg: 10.2625,
      firstName: "Jonnu",
      lastName: "Smith",
      position: "TE",
      team: "TE",
      id: "4144",
      gp: 17,
      overallRank: 72,
    },
    {
      rank: 5,
      points: 161.3,
      ppg: 9.488235294117647,
      firstName: "Mark",
      lastName: "Andrews",
      position: "TE",
      team: "TE",
      id: "5012",
      gp: 17,
      overallRank: 93,
    },
  ],
  RB: [
    {
      rank: 1,
      points: 338.8,
      ppg: 21.175,
      firstName: "Saquon",
      lastName: "Barkley",
      position: "RB",
      team: "RB",
      id: "4866",
      gp: 17,
      overallRank: 7,
    },
    {
      rank: 2,
      points: 326.9,
      ppg: 19.22941176470588,
      firstName: "Derrick",
      lastName: "Henry",
      position: "RB",
      team: "RB",
      id: "3198",
      gp: 17,
      overallRank: 8,
    },
    {
      rank: 3,
      points: 293.4,
      ppg: 18.3375,
      firstName: "Jahmyr",
      lastName: "Gibbs",
      position: "RB",
      team: "RB",
      id: "9221",
      gp: 17,
      overallRank: 11,
    },
    {
      rank: 4,
      points: 280.9,
      ppg: 17.55625,
      firstName: "Bijan",
      lastName: "Robinson",
      position: "RB",
      team: "RB",
      id: "9509",
      gp: 17,
      overallRank: 14,
    },
    {
      rank: 5,
      points: 264,
      ppg: 16.5,
      firstName: "Josh",
      lastName: "Jacobs",
      position: "RB",
      team: "RB",
      id: "5850",
      gp: 17,
      overallRank: 20,
    },
  ],
  DEF: [
    {
      rank: 1,
      points: 170,
      ppg: 10.625,
      firstName: "Denver",
      lastName: "Broncos",
      position: "DEF",
      team: "DEF",
      id: "DEN",
      gp: 17,
      overallRank: 64,
    },
    {
      rank: 2,
      points: 164,
      ppg: 10.25,
      firstName: "Minnesota",
      lastName: "Vikings",
      position: "DEF",
      team: "DEF",
      id: "MIN",
      gp: 17,
      overallRank: 84,
    },
    {
      rank: 3,
      points: 158,
      ppg: 9.294117647058824,
      firstName: "Pittsburgh",
      lastName: "Steelers",
      position: "DEF",
      team: "DEF",
      id: "PIT",
      gp: 17,
      overallRank: 99,
    },
    {
      rank: 5,
      points: 143,
      ppg: 8.9375,
      firstName: "Buffalo",
      lastName: "Bills",
      position: "DEF",
      team: "DEF",
      id: "BUF",
      gp: 17,
      overallRank: 112,
    },
    {
      rank: 6,
      points: 140,
      ppg: 8.75,
      firstName: "Philadelphia",
      lastName: "Eagles",
      position: "DEF",
      team: "DEF",
      id: "PHI",
      gp: 17,
      overallRank: 113,
    },
  ],
};

export const fakeRosterData = {
  "1": [
    {
      rank: 20,
      points: 12.8,
      overallRank: 64,
      ppg: 12.8,
      firstName: "Ricky",
      lastName: "Pearsall",
      position: "WR",
      team: "WR",
      id: "11638",
      gp: 1,
      rosterId: 1,
    },
    {
      rank: 88,
      points: 2.3,
      overallRank: 272,
      ppg: 2.3,
      firstName: "Elic",
      lastName: "Ayomanor",
      position: "WR",
      team: "WR",
      id: "12499",
      gp: 1,
      rosterId: 1,
    },
    {
      rank: 7,
      points: 12,
      overallRank: 76,
      ppg: 12,
      firstName: "Tyler",
      lastName: "Loop",
      position: "K",
      team: "K",
      id: "12711",
      gp: 1,
      rosterId: 1,
    },
    {
      rank: 9,
      points: 10.1,
      overallRank: 99,
      ppg: 10.1,
      firstName: "Zach",
      lastName: "Ertz",
      position: "TE",
      team: "TE",
      id: "1339",
      gp: 1,
      rosterId: 1,
    },
    {
      rank: 18,
      points: 12.7,
      overallRank: 67,
      ppg: 12.7,
      firstName: "Alvin",
      lastName: "Kamara",
      position: "RB",
      team: "RB",
      id: "4035",
      gp: 1,
      rosterId: 1,
    },
    {
      rank: 28,
      points: 8.82,
      overallRank: 126,
      ppg: 8.82,
      firstName: "Joe",
      lastName: "Burrow",
      position: "QB",
      team: "QB",
      id: "6770",
      gp: 1,
      rosterId: 1,
    },
    {
      rank: 1118,
      points: "__vue_devtool_undefined__",
      overallRank: 6115,
      ppg: "__vue_devtool_nan__",
      firstName: "Brandon",
      lastName: "Aiyuk",
      position: "WR",
      team: "WR",
      id: "6803",
      gp: "__vue_devtool_undefined__",
      rosterId: 1,
    },
    {
      rank: 70,
      points: 4,
      overallRank: 216,
      ppg: 4,
      firstName: "Nico",
      lastName: "Collins",
      position: "WR",
      team: "WR",
      id: "7569",
      gp: 1,
      rosterId: 1,
    },
    {
      rank: 2,
      points: 29.52,
      overallRank: 2,
      ppg: 29.52,
      firstName: "Justin",
      lastName: "Fields",
      position: "QB",
      team: "QB",
      id: "7591",
      gp: 1,
      rosterId: 1,
    },
    {
      rank: 24,
      points: 4.8,
      overallRank: 194,
      ppg: 4.8,
      firstName: "Jake",
      lastName: "Ferguson",
      position: "TE",
      team: "TE",
      id: "8110",
      gp: 1,
      rosterId: 1,
    },
    {
      rank: 29,
      points: 9.5,
      overallRank: 112,
      ppg: 9.5,
      firstName: "Drake",
      lastName: "London",
      position: "WR",
      team: "WR",
      id: "8112",
      gp: 1,
      rosterId: 1,
    },
    {
      rank: 40,
      points: 4.2,
      overallRank: 205,
      ppg: 4.2,
      firstName: "Brian",
      lastName: "Robinson",
      position: "RB",
      team: "RB",
      id: "8154",
      gp: 1,
      rosterId: 1,
    },
    {
      rank: 43,
      points: 3.8,
      overallRank: 223,
      ppg: 3.8,
      firstName: "Isiah",
      lastName: "Pacheco",
      position: "RB",
      team: "RB",
      id: "8205",
      gp: 1,
      rosterId: 1,
    },
    {
      rank: 63,
      points: 1.2,
      overallRank: 345,
      ppg: 1.2,
      firstName: "Tank",
      lastName: "Bigsby",
      position: "RB",
      team: "RB",
      id: "9225",
      gp: 1,
      rosterId: 1,
    },
    {
      rank: 1077,
      points: "__vue_devtool_undefined__",
      overallRank: 5618,
      ppg: "__vue_devtool_nan__",
      firstName: "Jordan",
      lastName: "Addison",
      position: "WR",
      team: "WR",
      id: "9756",
      gp: "__vue_devtool_undefined__",
      rosterId: 1,
    },
    {
      rank: 20,
      points: 3,
      overallRank: 240,
      ppg: 3,
      firstName: "Philadelphia",
      lastName: "Eagles",
      position: "DEF",
      team: "DEF",
      id: "PHI",
      gp: 1,
      rosterId: 1,
    },
  ],
  "2": [
    {
      rank: 21,
      points: 12.7,
      overallRank: 68,
      ppg: 12.7,
      firstName: "Rome",
      lastName: "Odunze",
      position: "WR",
      team: "WR",
      id: "11620",
      gp: 1,
      rosterId: 2,
    },
    {
      rank: 16,
      points: 13.3,
      overallRank: 61,
      ppg: 13.3,
      firstName: "Dylan",
      lastName: "Sampson",
      position: "RB",
      team: "RB",
      id: "12469",
      gp: 1,
      rosterId: 2,
    },
    {
      rank: 12,
      points: 14.2,
      overallRank: 50,
      ppg: 14.2,
      firstName: "Jacory",
      lastName: "Croskey-Merritt",
      position: "RB",
      team: "RB",
      id: "12533",
      gp: 1,
      rosterId: 2,
    },
    {
      rank: 9,
      points: 16.3,
      overallRank: 33,
      ppg: 16.3,
      firstName: "Keenan",
      lastName: "Allen",
      position: "WR",
      team: "WR",
      id: "1479",
      gp: 1,
      rosterId: 2,
    },
    {
      rank: 41,
      points: 7.6,
      overallRank: 149,
      ppg: 7.6,
      firstName: "Mike",
      lastName: "Evans",
      position: "WR",
      team: "WR",
      id: "2216",
      gp: 1,
      rosterId: 2,
    },
    {
      rank: 23,
      points: 5.2,
      overallRank: 186,
      ppg: 5.2,
      firstName: "David",
      lastName: "Njoku",
      position: "TE",
      team: "TE",
      id: "4033",
      gp: 1,
      rosterId: 2,
    },
    {
      rank: 30,
      points: 7.4,
      overallRank: 151,
      ppg: 7.4,
      firstName: "Tony",
      lastName: "Pollard",
      position: "RB",
      team: "RB",
      id: "5967",
      gp: 1,
      rosterId: 2,
    },
    {
      rank: 19,
      points: 12.8,
      overallRank: 63,
      ppg: 12.8,
      firstName: "Justin",
      lastName: "Jefferson",
      position: "WR",
      team: "WR",
      id: "6794",
      gp: 1,
      rosterId: 2,
    },
    {
      rank: 79,
      points: 3.1,
      overallRank: 238,
      ppg: 3.1,
      firstName: "DeVonta",
      lastName: "Smith",
      position: "WR",
      team: "WR",
      id: "7525",
      gp: 1,
      rosterId: 2,
    },
    {
      rank: 25,
      points: 5,
      overallRank: 191,
      ppg: 5,
      firstName: "Evan",
      lastName: "McPherson",
      position: "K",
      team: "K",
      id: "7839",
      gp: 1,
      rosterId: 2,
    },
    {
      rank: 14,
      points: 18.78,
      overallRank: 23,
      ppg: 18.78,
      firstName: "Brock",
      lastName: "Purdy",
      position: "QB",
      team: "QB",
      id: "8183",
      gp: 1,
      rosterId: 2,
    },
    {
      rank: 21,
      points: 12.1,
      overallRank: 72,
      ppg: 12.1,
      firstName: "Chase",
      lastName: "Brown",
      position: "RB",
      team: "RB",
      id: "9224",
      gp: 1,
      rosterId: 2,
    },
    {
      rank: 13,
      points: 14.9,
      overallRank: 45,
      ppg: 14.9,
      firstName: "Jaxon",
      lastName: "Smith-Njigba",
      position: "WR",
      team: "WR",
      id: "9488",
      gp: 1,
      rosterId: 2,
    },
    {
      rank: 32,
      points: -2,
      overallRank: 7433,
      ppg: -2,
      firstName: "Baltimore",
      lastName: "Ravens",
      position: "DEF",
      team: "DEF",
      id: "BAL",
      gp: 1,
      rosterId: 2,
    },
    {
      rank: 3,
      points: 12,
      overallRank: 73,
      ppg: 12,
      firstName: "Los Angeles",
      lastName: "Rams",
      position: "DEF",
      team: "DEF",
      id: "LAR",
      gp: 1,
      rosterId: 2,
    },
  ],
  "3": [
    {
      rank: 55,
      points: 2.1,
      overallRank: 278,
      ppg: 2.1,
      firstName: "Blake",
      lastName: "Corum",
      position: "RB",
      team: "RB",
      id: "11586",
      gp: 1,
      rosterId: 3,
    },
    {
      rank: 85,
      points: 2.6,
      overallRank: 259,
      ppg: 2.6,
      firstName: "Matthew",
      lastName: "Golden",
      position: "WR",
      team: "WR",
      id: "12501",
      gp: 1,
      rosterId: 3,
    },
    { rosterId: 3 },
    {
      rank: 4,
      points: 29.36,
      overallRank: 4,
      ppg: 29.36,
      firstName: "Lamar",
      lastName: "Jackson",
      position: "QB",
      team: "QB",
      id: "4881",
      gp: 1,
      rosterId: 3,
    },
    {
      rank: 37,
      points: 6,
      overallRank: 178,
      ppg: 6,
      firstName: "Nick",
      lastName: "Chubb",
      position: "RB",
      team: "RB",
      id: "4988",
      gp: 1,
      rosterId: 3,
    },
    {
      rank: 51,
      points: 1,
      overallRank: 387,
      ppg: 1,
      firstName: "Mark",
      lastName: "Andrews",
      position: "TE",
      team: "TE",
      id: "5012",
      gp: 1,
      rosterId: 3,
    },
    {
      rank: 11,
      points: 15.1,
      overallRank: 40,
      ppg: 15.1,
      firstName: "Courtland",
      lastName: "Sutton",
      position: "WR",
      team: "WR",
      id: "5045",
      gp: 1,
      rosterId: 3,
    },
    {
      rank: 27,
      points: 4,
      overallRank: 217,
      ppg: 4,
      firstName: "Chase",
      lastName: "McLaughlin",
      position: "K",
      team: "K",
      id: "6650",
      gp: 1,
      rosterId: 3,
    },
    {
      rank: 28,
      points: 8,
      overallRank: 135,
      ppg: 8,
      firstName: "D'Andre",
      lastName: "Swift",
      position: "RB",
      team: "RB",
      id: "6790",
      gp: 1,
      rosterId: 3,
    },
    {
      rank: 73,
      points: 0.5,
      overallRank: 439,
      ppg: 0.5,
      firstName: "Dameon",
      lastName: "Pierce",
      position: "RB",
      team: "RB",
      id: "8129",
      gp: 1,
      rosterId: 3,
    },
    {
      rank: 30,
      points: 9.4,
      overallRank: 113,
      ppg: 9.4,
      firstName: "Khalil",
      lastName: "Shakir",
      position: "WR",
      team: "WR",
      id: "8134",
      gp: 1,
      rosterId: 3,
    },
    {
      rank: 15,
      points: 13.4,
      overallRank: 59,
      ppg: 13.4,
      firstName: "Kyren",
      lastName: "Williams",
      position: "RB",
      team: "RB",
      id: "8150",
      gp: 1,
      rosterId: 3,
    },
    {
      rank: 2,
      points: 21.4,
      overallRank: 17,
      ppg: 21.4,
      firstName: "Bijan",
      lastName: "Robinson",
      position: "RB",
      team: "RB",
      id: "9509",
      gp: 1,
      rosterId: 3,
    },
    {
      rank: 1,
      points: 24.6,
      overallRank: 9,
      ppg: 24.6,
      firstName: "Zay",
      lastName: "Flowers",
      position: "WR",
      team: "WR",
      id: "9997",
      gp: 1,
      rosterId: 3,
    },
    {
      rank: 1,
      points: 16,
      overallRank: 35,
      ppg: 16,
      firstName: "Denver",
      lastName: "Broncos",
      position: "DEF",
      team: "DEF",
      id: "DEN",
      gp: 1,
      rosterId: 3,
    },
  ],
  "4": [
    {
      rank: 23,
      points: 12,
      overallRank: 77,
      ppg: 12,
      firstName: "Jayden",
      lastName: "Reed",
      position: "WR",
      team: "WR",
      id: "10222",
      gp: 1,
      rosterId: 4,
    },
    {
      rank: 1,
      points: 12.8,
      overallRank: 65,
      ppg: 12.8,
      firstName: "Brock",
      lastName: "Bowers",
      position: "TE",
      team: "TE",
      id: "11604",
      gp: 1,
      rosterId: 4,
    },
    {
      rank: 25,
      points: 10.4,
      overallRank: 96,
      ppg: 10.4,
      firstName: "Ladd",
      lastName: "McConkey",
      position: "WR",
      team: "WR",
      id: "11635",
      gp: 1,
      rosterId: 4,
    },
    {
      rank: 616,
      points: -0.2,
      overallRank: 7430,
      ppg: -0.2,
      firstName: "Kaleb",
      lastName: "Johnson",
      position: "RB",
      team: "RB",
      id: "12504",
      gp: 1,
      rosterId: 4,
    },
    {
      rank: 19,
      points: 8,
      overallRank: 140,
      ppg: 8,
      firstName: "Wil",
      lastName: "Lutz",
      position: "K",
      team: "K",
      id: "3678",
      gp: 1,
      rosterId: 4,
    },
    {
      rank: 12,
      points: 22.58,
      overallRank: 14,
      ppg: 22.58,
      firstName: "Baker",
      lastName: "Mayfield",
      position: "QB",
      team: "QB",
      id: "4892",
      gp: 1,
      rosterId: 4,
    },
    {
      rank: 26,
      points: 10.3,
      overallRank: 97,
      ppg: 10.3,
      firstName: "DK",
      lastName: "Metcalf",
      position: "WR",
      team: "WR",
      id: "5846",
      gp: 1,
      rosterId: 4,
    },
    {
      rank: 13,
      points: 13.8,
      overallRank: 54,
      ppg: 13.8,
      firstName: "J.K.",
      lastName: "Dobbins",
      position: "RB",
      team: "RB",
      id: "6806",
      gp: 1,
      rosterId: 4,
    },
    {
      rank: 91,
      points: 2,
      overallRank: 293,
      ppg: 2,
      firstName: "Rashod",
      lastName: "Bateman",
      position: "WR",
      team: "WR",
      id: "7571",
      gp: 1,
      rosterId: 4,
    },
    {
      rank: 44,
      points: 3.7,
      overallRank: 225,
      ppg: 3.7,
      firstName: "Rhamondre",
      lastName: "Stevenson",
      position: "RB",
      team: "RB",
      id: "7611",
      gp: 1,
      rosterId: 4,
    },
    {
      rank: 61,
      points: 4.6,
      overallRank: 199,
      ppg: 4.6,
      firstName: "Jameson",
      lastName: "Williams",
      position: "WR",
      team: "WR",
      id: "8148",
      gp: 1,
      rosterId: 4,
    },
    {
      rank: 27,
      points: 8,
      overallRank: 133,
      ppg: 8,
      firstName: "Jordan",
      lastName: "Mason",
      position: "RB",
      team: "RB",
      id: "8408",
      gp: 1,
      rosterId: 4,
    },
    {
      rank: 25,
      points: 10,
      overallRank: 103,
      ppg: 10,
      firstName: "Jahmyr",
      lastName: "Gibbs",
      position: "RB",
      team: "RB",
      id: "9221",
      gp: 1,
      rosterId: 4,
    },
    {
      rank: 26,
      points: 2,
      overallRank: 282,
      ppg: 2,
      firstName: "Buffalo",
      lastName: "Bills",
      position: "DEF",
      team: "DEF",
      id: "BUF",
      gp: 1,
      rosterId: 4,
    },
    {
      rank: 4,
      points: 12,
      overallRank: 74,
      ppg: 12,
      firstName: "Jacksonville",
      lastName: "Jaguars",
      position: "DEF",
      team: "DEF",
      id: "JAX",
      gp: 1,
      rosterId: 4,
    },
  ],
  "5": [
    {
      rank: 22,
      points: 7,
      overallRank: 164,
      ppg: 7,
      firstName: "Jake",
      lastName: "Bates",
      position: "K",
      team: "K",
      id: "11539",
      gp: 1,
      rosterId: 5,
    },
    {
      rank: 27,
      points: 8.84,
      overallRank: 125,
      ppg: 8.84,
      firstName: "Bo",
      lastName: "Nix",
      position: "QB",
      team: "QB",
      id: "11563",
      gp: 1,
      rosterId: 5,
    },
    {
      rank: 56,
      points: 1.9,
      overallRank: 323,
      ppg: 1.9,
      firstName: "Cam",
      lastName: "Skattebo",
      position: "RB",
      team: "RB",
      id: "12481",
      gp: 1,
      rosterId: 5,
    },
    {
      rank: 32,
      points: 2.48,
      overallRank: 267,
      ppg: 2.48,
      firstName: "Cam",
      lastName: "Ward",
      position: "QB",
      team: "QB",
      id: "12522",
      gp: 1,
      rosterId: 5,
    },
    {
      rank: 1,
      points: 28.7,
      overallRank: 5,
      ppg: 28.7,
      firstName: "Derrick",
      lastName: "Henry",
      position: "RB",
      team: "RB",
      id: "3198",
      gp: 1,
      rosterId: 5,
    },
    {
      rank: 53,
      points: 6,
      overallRank: 179,
      ppg: 6,
      firstName: "Tyreek",
      lastName: "Hill",
      position: "WR",
      team: "WR",
      id: "3321",
      gp: 1,
      rosterId: 5,
    },
    {
      rank: 45,
      points: 7.1,
      overallRank: 158,
      ppg: 7.1,
      firstName: "DJ",
      lastName: "Moore",
      position: "WR",
      team: "WR",
      id: "4983",
      gp: 1,
      rosterId: 5,
    },
    {
      rank: 35,
      points: 3,
      overallRank: 248,
      ppg: 3,
      firstName: "T.J.",
      lastName: "Hockenson",
      position: "TE",
      team: "TE",
      id: "5844",
      gp: 1,
      rosterId: 5,
    },
    {
      rank: 32,
      points: 9.1,
      overallRank: 117,
      ppg: 9.1,
      firstName: "Jerry",
      lastName: "Jeudy",
      position: "WR",
      team: "WR",
      id: "6783",
      gp: 1,
      rosterId: 5,
    },
    {
      rank: 83,
      points: 2.6,
      overallRank: 256,
      ppg: 2.6,
      firstName: "Jauan",
      lastName: "Jennings",
      position: "WR",
      team: "WR",
      id: "7049",
      gp: 1,
      rosterId: 5,
    },
    {
      rank: 52,
      points: 2.4,
      overallRank: 269,
      ppg: 2.4,
      firstName: "Tyler",
      lastName: "Allgeier",
      position: "RB",
      team: "RB",
      id: "8132",
      gp: 1,
      rosterId: 5,
    },
    {
      rank: 6,
      points: 19,
      overallRank: 22,
      ppg: 19,
      firstName: "Garrett",
      lastName: "Wilson",
      position: "WR",
      team: "WR",
      id: "8146",
      gp: 1,
      rosterId: 5,
    },
    {
      rank: 50,
      points: 6.3,
      overallRank: 169,
      ppg: 6.3,
      firstName: "Rashid",
      lastName: "Shaheed",
      position: "WR",
      team: "WR",
      id: "8676",
      gp: 1,
      rosterId: 5,
    },
    {
      rank: 10,
      points: 15,
      overallRank: 41,
      ppg: 15,
      firstName: "De'Von",
      lastName: "Achane",
      position: "RB",
      team: "RB",
      id: "9226",
      gp: 1,
      rosterId: 5,
    },
    {
      rank: 17,
      points: 5,
      overallRank: 189,
      ppg: 5,
      firstName: "Minnesota",
      lastName: "Vikings",
      position: "DEF",
      team: "DEF",
      id: "MIN",
      gp: 1,
      rosterId: 5,
    },
  ],
  "6": [
    {
      rank: 19,
      points: 12.5,
      overallRank: 69,
      ppg: 12.5,
      firstName: "Bucky",
      lastName: "Irving",
      position: "RB",
      team: "RB",
      id: "11584",
      gp: 1,
      rosterId: 6,
    },
    {
      rank: 1211,
      points: "__vue_devtool_undefined__",
      overallRank: 7168,
      ppg: "__vue_devtool_nan__",
      firstName: "Xavier",
      lastName: "Worthy",
      position: "WR",
      team: "WR",
      id: "11624",
      gp: 1,
      rosterId: 6,
    },
    {
      rank: 33,
      points: 7.1,
      overallRank: 160,
      ppg: 7.1,
      firstName: "Omarion",
      lastName: "Hampton",
      position: "RB",
      team: "RB",
      id: "12507",
      gp: 1,
      rosterId: 6,
    },
    {
      rank: 5,
      points: 11.4,
      overallRank: 82,
      ppg: 11.4,
      firstName: "Tyler",
      lastName: "Warren",
      position: "TE",
      team: "TE",
      id: "12518",
      gp: 1,
      rosterId: 6,
    },
    {
      rank: 46,
      points: 7.1,
      overallRank: 159,
      ppg: 7.1,
      firstName: "Davante",
      lastName: "Adams",
      position: "WR",
      team: "WR",
      id: "2133",
      gp: 1,
      rosterId: 6,
    },
    {
      rank: 21,
      points: 11.9,
      overallRank: 78,
      ppg: 11.9,
      firstName: "Jared",
      lastName: "Goff",
      position: "QB",
      team: "QB",
      id: "3163",
      gp: 1,
      rosterId: 6,
    },
    {
      rank: 8,
      points: 16.4,
      overallRank: 32,
      ppg: 16.4,
      firstName: "Saquon",
      lastName: "Barkley",
      position: "RB",
      team: "RB",
      id: "4866",
      gp: 1,
      rosterId: 6,
    },
    {
      rank: 23,
      points: 11.32,
      overallRank: 83,
      ppg: 11.32,
      firstName: "Trevor",
      lastName: "Lawrence",
      position: "QB",
      team: "QB",
      id: "7523",
      gp: 1,
      rosterId: 6,
    },
    {
      rank: 57,
      points: 5,
      overallRank: 192,
      ppg: 5,
      firstName: "Jaylen",
      lastName: "Waddle",
      position: "WR",
      team: "WR",
      id: "7526",
      gp: 1,
      rosterId: 6,
    },
    {
      rank: 62,
      points: 1.5,
      overallRank: 336,
      ppg: 1.5,
      firstName: "Najee",
      lastName: "Harris",
      position: "RB",
      team: "RB",
      id: "7528",
      gp: 1,
      rosterId: 6,
    },
    {
      rank: 13,
      points: 9,
      overallRank: 120,
      ppg: 9,
      firstName: "Cameron",
      lastName: "Dicker",
      position: "K",
      team: "K",
      id: "8259",
      gp: 1,
      rosterId: 6,
    },
    {
      rank: 89,
      points: 2.2,
      overallRank: 273,
      ppg: 2.2,
      firstName: "Josh",
      lastName: "Downs",
      position: "WR",
      team: "WR",
      id: "9500",
      gp: 1,
      rosterId: 6,
    },
    {
      rank: 547,
      points: "__vue_devtool_undefined__",
      overallRank: 5620,
      ppg: "__vue_devtool_nan__",
      firstName: "Tyjae",
      lastName: "Spears",
      position: "RB",
      team: "RB",
      id: "9508",
      gp: "__vue_devtool_undefined__",
      rosterId: 6,
    },
    {
      rank: 24,
      points: 10.7,
      overallRank: 92,
      ppg: 10.7,
      firstName: "Zach",
      lastName: "Charbonnet",
      position: "RB",
      team: "RB",
      id: "9753",
      gp: 1,
      rosterId: 6,
    },
    {
      rank: 14,
      points: 6,
      overallRank: 176,
      ppg: 6,
      firstName: "Houston",
      lastName: "Texans",
      position: "DEF",
      team: "DEF",
      id: "HOU",
      gp: 1,
      rosterId: 6,
    },
    {
      rank: 13,
      points: 6,
      overallRank: 175,
      ppg: 6,
      firstName: "New England",
      lastName: "Patriots",
      position: "DEF",
      team: "DEF",
      id: "NE",
      gp: 1,
      rosterId: 6,
    },
  ],
  "7": [
    {
      rank: 8,
      points: 11,
      overallRank: 90,
      ppg: 11,
      firstName: "Brandon",
      lastName: "Aubrey",
      position: "K",
      team: "K",
      id: "11533",
      gp: 1,
      rosterId: 7,
    },
    {
      rank: 72,
      points: 0.6,
      overallRank: 437,
      ppg: 0.6,
      firstName: "Ray",
      lastName: "Davis",
      position: "RB",
      team: "RB",
      id: "11575",
      gp: 1,
      rosterId: 7,
    },
    {
      rank: 39,
      points: 4.5,
      overallRank: 201,
      ppg: 4.5,
      firstName: "Tyrone",
      lastName: "Tracy",
      position: "RB",
      team: "RB",
      id: "11655",
      gp: 1,
      rosterId: 7,
    },
    {
      rank: 64,
      points: 4.2,
      overallRank: 207,
      ppg: 4.2,
      firstName: "Jayden",
      lastName: "Higgins",
      position: "WR",
      team: "WR",
      id: "12484",
      gp: 1,
      rosterId: 7,
    },
    {
      rank: 20,
      points: 12.4,
      overallRank: 70,
      ppg: 12.4,
      firstName: "James",
      lastName: "Conner",
      position: "RB",
      team: "RB",
      id: "4137",
      gp: 1,
      rosterId: 7,
    },
    {
      rank: 1,
      points: 38.76,
      overallRank: 1,
      ppg: 38.76,
      firstName: "Josh",
      lastName: "Allen",
      position: "QB",
      team: "QB",
      id: "4984",
      gp: 1,
      rosterId: 7,
    },
    {
      rank: 5,
      points: 19.1,
      overallRank: 21,
      ppg: 19.1,
      firstName: "Deebo",
      lastName: "Samuel",
      position: "WR",
      team: "WR",
      id: "5872",
      gp: 1,
      rosterId: 7,
    },
    {
      rank: 16,
      points: 13.7,
      overallRank: 55,
      ppg: 13.7,
      firstName: "Jakobi",
      lastName: "Meyers",
      position: "WR",
      team: "WR",
      id: "5947",
      gp: 1,
      rosterId: 7,
    },
    {
      rank: 77,
      points: 3.6,
      overallRank: 230,
      ppg: 3.6,
      firstName: "Ja'Marr",
      lastName: "Chase",
      position: "WR",
      team: "WR",
      id: "7564",
      gp: 1,
      rosterId: 7,
    },
    {
      rank: 7,
      points: 16.4,
      overallRank: 31,
      ppg: 16.4,
      firstName: "Chuba",
      lastName: "Hubbard",
      position: "RB",
      team: "RB",
      id: "7594",
      gp: 1,
      rosterId: 7,
    },
    {
      rank: 35,
      points: 8.6,
      overallRank: 128,
      ppg: 8.6,
      firstName: "Joshua",
      lastName: "Palmer",
      position: "WR",
      team: "WR",
      id: "7670",
      gp: 1,
      rosterId: 7,
    },
    {
      rank: 4,
      points: 18.7,
      overallRank: 24,
      ppg: 18.7,
      firstName: "James",
      lastName: "Cook",
      position: "RB",
      team: "RB",
      id: "8138",
      gp: 1,
      rosterId: 7,
    },
    {
      rank: 15,
      points: 8.9,
      overallRank: 123,
      ppg: 8.9,
      firstName: "Tucker",
      lastName: "Kraft",
      position: "TE",
      team: "TE",
      id: "9484",
      gp: 1,
      rosterId: 7,
    },
    {
      rank: 112,
      points: 0.7,
      overallRank: 430,
      ppg: 0.7,
      firstName: "Marvin",
      lastName: "Mims",
      position: "WR",
      team: "WR",
      id: "9494",
      gp: 1,
      rosterId: 7,
    },
    {
      rank: 8,
      points: 10,
      overallRank: 101,
      ppg: 10,
      firstName: "Washington",
      lastName: "Commanders",
      position: "DEF",
      team: "DEF",
      id: "WAS",
      gp: 1,
      rosterId: 7,
    },
  ],
  "8": [
    {
      rank: 11,
      points: 23.22,
      overallRank: 13,
      ppg: 23.22,
      firstName: "J.J.",
      lastName: "McCarthy",
      position: "QB",
      team: "QB",
      id: "11565",
      gp: 1,
      rosterId: 8,
    },
    {
      rank: 37,
      points: 8.5,
      overallRank: 131,
      ppg: 8.5,
      firstName: "Brian",
      lastName: "Thomas",
      position: "WR",
      team: "WR",
      id: "11631",
      gp: 1,
      rosterId: 8,
    },
    {
      rank: 597,
      points: "__vue_devtool_undefined__",
      overallRank: 7157,
      ppg: "__vue_devtool_nan__",
      firstName: "Isaac",
      lastName: "Guerendo",
      position: "RB",
      team: "RB",
      id: "11651",
      gp: 1,
      rosterId: 8,
    },
    {
      rank: 51,
      points: 6.3,
      overallRank: 171,
      ppg: 6.3,
      firstName: "Travis",
      lastName: "Hunter",
      position: "WR",
      team: "WR",
      id: "12530",
      gp: 1,
      rosterId: 8,
    },
    {
      rank: 92,
      points: 2,
      overallRank: 307,
      ppg: 2,
      firstName: "Adam",
      lastName: "Thielen",
      position: "WR",
      team: "WR",
      id: "1689",
      gp: 1,
      rosterId: 8,
    },
    {
      rank: 5,
      points: 14,
      overallRank: 53,
      ppg: 14,
      firstName: "Chris",
      lastName: "Boswell",
      position: "K",
      team: "K",
      id: "1945",
      gp: 1,
      rosterId: 8,
    },
    {
      rank: 29,
      points: 7.82,
      overallRank: 145,
      ppg: 7.82,
      firstName: "Dak",
      lastName: "Prescott",
      position: "QB",
      team: "QB",
      id: "3294",
      gp: 1,
      rosterId: 8,
    },
    {
      rank: 574,
      points: "__vue_devtool_undefined__",
      overallRank: 6422,
      ppg: "__vue_devtool_nan__",
      firstName: "Joe",
      lastName: "Mixon",
      position: "RB",
      team: "RB",
      id: "4018",
      gp: "__vue_devtool_undefined__",
      rosterId: 8,
    },
    {
      rank: 5,
      points: 18.7,
      overallRank: 25,
      ppg: 18.7,
      firstName: "Christian",
      lastName: "McCaffrey",
      position: "RB",
      team: "RB",
      id: "4034",
      gp: 1,
      rosterId: 8,
    },
    {
      rank: 11,
      points: 10,
      overallRank: 107,
      ppg: 10,
      firstName: "Jonnu",
      lastName: "Smith",
      position: "TE",
      team: "TE",
      id: "4144",
      gp: 1,
      rosterId: 8,
    },
    {
      rank: 35,
      points: 6.3,
      overallRank: 170,
      ppg: 6.3,
      firstName: "David",
      lastName: "Montgomery",
      position: "RB",
      team: "RB",
      id: "5892",
      gp: 1,
      rosterId: 8,
    },
    {
      rank: 58,
      points: 4.8,
      overallRank: 196,
      ppg: 4.8,
      firstName: "Tee",
      lastName: "Higgins",
      position: "WR",
      team: "WR",
      id: "6801",
      gp: 1,
      rosterId: 8,
    },
    {
      rank: 502,
      points: "__vue_devtool_undefined__",
      overallRank: 5835,
      ppg: "__vue_devtool_nan__",
      firstName: "Cade",
      lastName: "Otton",
      position: "TE",
      team: "TE",
      id: "8111",
      gp: 1,
      rosterId: 8,
    },
    {
      rank: 33,
      points: 8.9,
      overallRank: 124,
      ppg: 8.9,
      firstName: "Chris",
      lastName: "Olave",
      position: "WR",
      team: "WR",
      id: "8144",
      gp: 1,
      rosterId: 8,
    },
    {
      rank: 9,
      points: 15.5,
      overallRank: 39,
      ppg: 15.5,
      firstName: "Breece",
      lastName: "Hall",
      position: "RB",
      team: "RB",
      id: "8155",
      gp: 1,
      rosterId: 8,
    },
    {
      rank: 23,
      points: 2,
      overallRank: 279,
      ppg: 2,
      firstName: "Pittsburgh",
      lastName: "Steelers",
      position: "DEF",
      team: "DEF",
      id: "PIT",
      gp: 1,
      rosterId: 8,
    },
  ],
  "9": [
    { rosterId: 9 },
    {
      rank: 2,
      points: 12.8,
      overallRank: 66,
      ppg: 12.8,
      firstName: "Dalton",
      lastName: "Kincaid",
      position: "TE",
      team: "TE",
      id: "10236",
      gp: 1,
      rosterId: 9,
    },
    {
      rank: 3,
      points: 15,
      overallRank: 44,
      ppg: 15,
      firstName: "Cam",
      lastName: "Little",
      position: "K",
      team: "K",
      id: "11786",
      gp: 1,
      rosterId: 9,
    },
    {
      rank: 31,
      points: 7.4,
      overallRank: 152,
      ppg: 7.4,
      firstName: "RJ",
      lastName: "Harvey",
      position: "RB",
      team: "RB",
      id: "12489",
      gp: 1,
      rosterId: 9,
    },
    {
      rank: 588,
      points: "__vue_devtool_undefined__",
      overallRank: 6888,
      ppg: "__vue_devtool_nan__",
      firstName: "Quinshon",
      lastName: "Judkins",
      position: "RB",
      team: "RB",
      id: "12512",
      gp: 1,
      rosterId: 9,
    },
    {
      rank: 3,
      points: 11.7,
      overallRank: 79,
      ppg: 11.7,
      firstName: "Travis",
      lastName: "Kelce",
      position: "TE",
      team: "TE",
      id: "1466",
      gp: 1,
      rosterId: 9,
    },
    {
      rank: 14,
      points: 13.5,
      overallRank: 58,
      ppg: 13.5,
      firstName: "Josh",
      lastName: "Jacobs",
      position: "RB",
      team: "RB",
      id: "5850",
      gp: 1,
      rosterId: 9,
    },
    {
      rank: 74,
      points: 3.7,
      overallRank: 226,
      ppg: 3.7,
      firstName: "Terry",
      lastName: "McLaurin",
      position: "WR",
      team: "WR",
      id: "5927",
      gp: 1,
      rosterId: 9,
    },
    {
      rank: 8,
      points: 24.28,
      overallRank: 10,
      ppg: 24.28,
      firstName: "Jalen",
      lastName: "Hurts",
      position: "QB",
      team: "QB",
      id: "6904",
      gp: 1,
      rosterId: 9,
    },
    { rosterId: 9 },
    {
      rank: 6,
      points: 17.1,
      overallRank: 29,
      ppg: 17.1,
      firstName: "Travis",
      lastName: "Etienne",
      position: "RB",
      team: "RB",
      id: "7543",
      gp: 1,
      rosterId: 9,
    },
    {
      rank: 48,
      points: 6.5,
      overallRank: 167,
      ppg: 6.5,
      firstName: "Amon-Ra",
      lastName: "St. Brown",
      position: "WR",
      team: "WR",
      id: "7547",
      gp: 1,
      rosterId: 9,
    },
    {
      rank: 12,
      points: 9.4,
      overallRank: 114,
      ppg: 9.4,
      firstName: "Kyle",
      lastName: "Pitts",
      position: "TE",
      team: "TE",
      id: "7553",
      gp: 1,
      rosterId: 9,
    },
    {
      rank: 62,
      points: 4.5,
      overallRank: 200,
      ppg: 4.5,
      firstName: "George",
      lastName: "Pickens",
      position: "WR",
      team: "WR",
      id: "8137",
      gp: 1,
      rosterId: 9,
    },
    {
      rank: 5,
      points: 11,
      overallRank: 86,
      ppg: 11,
      firstName: "San Francisco",
      lastName: "49ers",
      position: "DEF",
      team: "DEF",
      id: "SF",
      gp: 1,
      rosterId: 9,
    },
  ],
  "10": [
    {
      rank: 1234,
      points: "__vue_devtool_undefined__",
      overallRank: 7418,
      ppg: "__vue_devtool_nan__",
      firstName: "Rashee",
      lastName: "Rice",
      position: "WR",
      team: "WR",
      id: "10229",
      gp: "__vue_devtool_undefined__",
      rosterId: 10,
    },
    {
      rank: 34,
      points: 6.9,
      overallRank: 165,
      ppg: 6.9,
      firstName: "Braelon",
      lastName: "Allen",
      position: "RB",
      team: "RB",
      id: "11576",
      gp: 1,
      rosterId: 10,
    },
    {
      rank: 4,
      points: 21.2,
      overallRank: 18,
      ppg: 21.2,
      firstName: "Keon",
      lastName: "Coleman",
      position: "WR",
      team: "WR",
      id: "11637",
      gp: 1,
      rosterId: 10,
    },
    { rosterId: 10 },
    {
      rank: 31,
      points: 9.3,
      overallRank: 115,
      ppg: 9.3,
      firstName: "Tetairoa",
      lastName: "McMillan",
      position: "WR",
      team: "WR",
      id: "12526",
      gp: 1,
      rosterId: 10,
    },
    {
      rank: 54,
      points: 5.5,
      overallRank: 183,
      ppg: 5.5,
      firstName: "Dont'e",
      lastName: "Thornton",
      position: "WR",
      team: "WR",
      id: "12541",
      gp: 1,
      rosterId: 10,
    },
    {
      rank: 34,
      points: 8.7,
      overallRank: 127,
      ppg: 8.7,
      firstName: "Stefon",
      lastName: "Diggs",
      position: "WR",
      team: "WR",
      id: "2449",
      gp: 1,
      rosterId: 10,
    },
    {
      rank: 4,
      points: 14,
      overallRank: 52,
      ppg: 14,
      firstName: "Ka'imi",
      lastName: "Fairbairn",
      position: "K",
      team: "K",
      id: "3451",
      gp: 1,
      rosterId: 10,
    },
    {
      rank: 16,
      points: 18.32,
      overallRank: 27,
      ppg: 18.32,
      firstName: "Kyler",
      lastName: "Murray",
      position: "QB",
      team: "QB",
      id: "5849",
      gp: 1,
      rosterId: 10,
    },
    {
      rank: 100,
      points: 1.3,
      overallRank: 343,
      ppg: 1.3,
      firstName: "A.J.",
      lastName: "Brown",
      position: "WR",
      team: "WR",
      id: "5859",
      gp: 1,
      rosterId: 10,
    },
    {
      rank: 15,
      points: 14.5,
      overallRank: 47,
      ppg: 14.5,
      firstName: "CeeDee",
      lastName: "Lamb",
      position: "WR",
      team: "WR",
      id: "6786",
      gp: 1,
      rosterId: 10,
    },
    {
      rank: 3,
      points: 19.4,
      overallRank: 20,
      ppg: 19.4,
      firstName: "Javonte",
      lastName: "Williams",
      position: "RB",
      team: "RB",
      id: "7588",
      gp: 1,
      rosterId: 10,
    },
    {
      rank: 13,
      points: 9.1,
      overallRank: 116,
      ppg: 9.1,
      firstName: "Trey",
      lastName: "McBride",
      position: "TE",
      team: "TE",
      id: "8130",
      gp: 1,
      rosterId: 10,
    },
    {
      rank: 42,
      points: 3.9,
      overallRank: 220,
      ppg: 3.9,
      firstName: "Kenneth",
      lastName: "Walker",
      position: "RB",
      team: "RB",
      id: "8151",
      gp: 1,
      rosterId: 10,
    },
    {
      rank: 11,
      points: 7,
      overallRank: 161,
      ppg: 7,
      firstName: "Seattle",
      lastName: "Seahawks",
      position: "DEF",
      team: "DEF",
      id: "SEA",
      gp: 1,
      rosterId: 10,
    },
  ],
};
