export const fakePlayerRankings = {
  K: [
    {
      rank: 1,
      points: 188,
      ppg: 11.058823529411764,
      firstName: "Chris",
      lastName: "Boswell",
      position: "K",
      team: "K",
      id: "1945",
    },
    {
      rank: 2,
      points: 171,
      ppg: 10.6875,
      firstName: "Brandon",
      lastName: "Aubrey",
      position: "K",
      team: "K",
      id: "11533",
    },
    {
      rank: 3,
      points: 160,
      ppg: 10,
      firstName: "Ka'imi",
      lastName: "Fairbairn",
      position: "K",
      team: "K",
      id: "3451",
    },
    {
      rank: 4,
      points: 159,
      ppg: 9.9375,
      firstName: "Cameron",
      lastName: "Dicker",
      position: "K",
      team: "K",
      id: "8259",
    },
    {
      rank: 5,
      points: 152,
      ppg: 9.5,
      firstName: "Jason",
      lastName: "Sanders",
      position: "K",
      team: "K",
      id: "5119",
    },
  ],
  QB: [
    {
      rank: 1,
      points: 434.38,
      ppg: 25.551764705882352,
      firstName: "Lamar",
      lastName: "Jackson",
      position: "QB",
      team: "QB",
      id: "4881",
    },
    {
      rank: 2,
      points: 385.04,
      ppg: 24.065,
      firstName: "Josh",
      lastName: "Allen",
      position: "QB",
      team: "QB",
      id: "4984",
    },
    {
      rank: 3,
      points: 381.82,
      ppg: 22.46,
      firstName: "Joe",
      lastName: "Burrow",
      position: "QB",
      team: "QB",
      id: "6770",
    },
    {
      rank: 4,
      points: 360.6,
      ppg: 22.5375,
      firstName: "Jayden",
      lastName: "Daniels",
      position: "QB",
      team: "QB",
      id: "11566",
    },
    {
      rank: 5,
      points: 359.16,
      ppg: 22.4475,
      firstName: "Baker",
      lastName: "Mayfield",
      position: "QB",
      team: "QB",
      id: "4892",
    },
  ],
  WR: [
    {
      rank: 1,
      points: 339.5,
      ppg: 19.970588235294116,
      firstName: "Ja'Marr",
      lastName: "Chase",
      position: "WR",
      team: "WR",
      id: "7564",
    },
    {
      rank: 2,
      points: 259.08,
      ppg: 16.1925,
      firstName: "Justin",
      lastName: "Jefferson",
      position: "WR",
      team: "WR",
      id: "6794",
    },
    {
      rank: 3,
      points: 247.98,
      ppg: 15.49875,
      firstName: "Amon-Ra",
      lastName: "St. Brown",
      position: "WR",
      team: "WR",
      id: "7547",
    },
    {
      rank: 4,
      points: 226.7,
      ppg: 14.16875,
      firstName: "Brian",
      lastName: "Thomas",
      position: "WR",
      team: "WR",
      id: "11631",
    },
    {
      rank: 5,
      points: 212.9,
      ppg: 14.193333333333333,
      firstName: "CeeDee",
      lastName: "Lamb",
      position: "WR",
      team: "WR",
      id: "6786",
    },
  ],
  TE: [
    {
      rank: 1,
      points: 193.9,
      ppg: 13.85,
      firstName: "George",
      lastName: "Kittle",
      position: "TE",
      team: "TE",
      id: "4217",
    },
    {
      rank: 2,
      points: 193.7,
      ppg: 12.10625,
      firstName: "Brock",
      lastName: "Bowers",
      position: "TE",
      team: "TE",
      id: "11604",
    },
    {
      rank: 3,
      points: 178.3,
      ppg: 11.886666666666667,
      firstName: "Trey",
      lastName: "McBride",
      position: "TE",
      team: "TE",
      id: "8130",
    },
    {
      rank: 4,
      points: 164.2,
      ppg: 10.2625,
      firstName: "Jonnu",
      lastName: "Smith",
      position: "TE",
      team: "TE",
      id: "4144",
    },
    {
      rank: 5,
      points: 161.3,
      ppg: 9.488235294117647,
      firstName: "Mark",
      lastName: "Andrews",
      position: "TE",
      team: "TE",
      id: "5012",
    },
  ],
  RB: [
    {
      rank: 1,
      points: 338.8,
      ppg: 21.175,
      firstName: "Saquon",
      lastName: "Barkley",
      position: "RB",
      team: "RB",
      id: "4866",
    },
    {
      rank: 2,
      points: 326.9,
      ppg: 19.22941176470588,
      firstName: "Derrick",
      lastName: "Henry",
      position: "RB",
      team: "RB",
      id: "3198",
    },
    {
      rank: 3,
      points: 293.4,
      ppg: 18.3375,
      firstName: "Jahmyr",
      lastName: "Gibbs",
      position: "RB",
      team: "RB",
      id: "9221",
    },
    {
      rank: 4,
      points: 280.9,
      ppg: 17.55625,
      firstName: "Bijan",
      lastName: "Robinson",
      position: "RB",
      team: "RB",
      id: "9509",
    },
    {
      rank: 5,
      points: 264,
      ppg: 16.5,
      firstName: "Josh",
      lastName: "Jacobs",
      position: "RB",
      team: "RB",
      id: "5850",
    },
  ],
  DEF: [
    {
      rank: 1,
      points: 170,
      ppg: 10.625,
      firstName: "Denver",
      lastName: "Broncos",
      position: "DEF",
      team: "DEF",
      id: "DEN",
    },
    {
      rank: 2,
      points: 164,
      ppg: 10.25,
      firstName: "Minnesota",
      lastName: "Vikings",
      position: "DEF",
      team: "DEF",
      id: "MIN",
    },
    {
      rank: 3,
      points: 158,
      ppg: 9.294117647058824,
      firstName: "Pittsburgh",
      lastName: "Steelers",
      position: "DEF",
      team: "DEF",
      id: "PIT",
    },
    {
      rank: 5,
      points: 143,
      ppg: 8.9375,
      firstName: "Buffalo",
      lastName: "Bills",
      position: "DEF",
      team: "DEF",
      id: "BUF",
    },
    {
      rank: 6,
      points: 140,
      ppg: 8.75,
      firstName: "Philadelphia",
      lastName: "Eagles",
      position: "DEF",
      team: "DEF",
      id: "PHI",
    },
  ],
};
